### ISSUE TITLE
Store caches errors

### ISSUE THREAD

**Issue by PaulWoitaschek** [NYTimes/Store#100]
I'm not sure if this is intended behavior. If an `Observable` errors, subsequent calls to `get` just repeat that error.
I would expect the store to retry after an error.

```java
public class DontCacheErrorsTest {

    private boolean shouldThrow;
    private Store<Integer> store;

    @Before
    public void setUp() {
        store = StoreBuilder.<Integer>builder()
                .fetcher(barCode -> Observable.fromCallable(() -> {
                    if (shouldThrow) throw new RuntimeException();
                    else return 0;
                }))
                .open();
    }

    @Test
    public void testStoreDoesntCacheErrors() throws InterruptedException {
        BarCode barcode = new BarCode("bar", "code");

        shouldThrow = true;
        store.get(barcode).test()
                .awaitTerminalEvent()
                .assertError(Exception.class);

        shouldThrow = false;
        store.get(barcode).test()
                .awaitTerminalEvent()
                .assertNoErrors();
    }
}
```

**Comment by pavlospt** [comment]
Agree on that issue, had stumble upon it before but did not have the time to open it. Retrying though is kind of obtrusive. I would expect that the Store would not write a resource and just hit the `fetcher` again.

**Comment by digitalbuddha** [comment]
Issue is due to inflight being unaware if it is a good or error response and caching it for 1 min.  I'll make a change that will clear inflight if an error is read.  I don't believe any additional retry logic is needed.  Thanks for reporting PR coming....

**Comment by PaulWoitaschek** [comment]
I was a little unclear. With retry I mean that in like in my test the second `get` should call the fetcher again.
