### ISSUE TITLE
Add ClearDisk interface

### ISSUE THREAD

**Issue by digitalbuddha** [NYTimes/Store#102]
in conjunction with #68 we should have a way to clear memory and disk cache.  Current idea is add:

Store:
`    void clear(BarCode barCode);
`
Builder:
`   builder.diskClearer(barcode->//deletes entry from user's persister);`

**Comment by pavlospt** [comment]
@digitalbuddha it should also provide an interface for whole disk cache clear I suppose. But that I guess would be exposed internally from the FileSystem ?

**Comment by PaulWoitaschek** [comment]
Why would one want to clear one without the other? (cache & persistence)

Why shouldn't it be mandatory for persisters to be able to clear their data?

**Comment by digitalbuddha** [comment]
For now backwards compatibility. I'll Deprecated and consider removing in v2.

**Comment by PaulWoitaschek** [comment]
What about defining a common interface like `Clearable` that both the cache and the persister can implement? Then upon calling `.clear` throwing a `NotSupportedException` if the persister is not an instance of `Clearable`?

**Comment by digitalbuddha** [comment]
Not following, mind explaining what you mean?  Also the memory cache is currently a guava cache which we don't have control over interface.  I guess it can be wrapped but yeah mind explaining what you mean?

**Comment by PaulWoitaschek** [comment]
If I understand you correctly, you want to give the option to add a `DiskClearer` to the store that you supply through the builder.
This class responsibility is to clear data from the `Persister`.

So my suggestion is to instead of having a separate `DiskClearer` to have an interface that `Persisters` can implement to indicate that they know how to clear data.
Then if someone would call `clear` without his `Persister` implmenting `Clearable` an `NotSupportedException("The supplied persister must implement Clearable")`

Or do I get you completely wrong?

**Comment by digitalbuddha** [comment]
Sure that makes sense.  I was trying to handle the lambda case in the way that `DiskRead` & `DiskWrite` exist for when a Store is instantiated.  So maybe instead it should just be an additional override to `.persister(reader, writer, clearer)` while also allowing the interface to be implemented by someone implementing the current `Persister` interface. Thanks for feedback!

**Comment by digitalbuddha** [comment]
@PaulWoitaschek I'm starting to side with you. If there is a memory and disk cache why would someone only want to clear the memory one?  I'll instead rename `clearMemory` to `clear` and then clear disk when the disk implements `clearable` thank you for feedback

**Comment by pavlospt** [comment]
@digitalbuddha Is there a chance to have memory and disk cache side-by-side?

**Comment by digitalbuddha** [comment]
You can have both but I don't see a use case where you want to clear your memory cache but not your disk. If that is your use case you can always not implement clearable in your persister
