### ISSUE TITLE
Add resolver to file system 

### ISSUE THREAD

**Issue by digitalbuddha** [NYTimes/Store#116]
Since users can supply their own type for the Key (instead of Barcode), we need to make sure any key being created implements an `String id()` so that the file system will know how to turn the key into a filename.   Ideally this is only a requirement if using the FileSystem

**Comment by pavlospt** [comment]
How will you limit it to FileSystem implementations? Would you go with another interface and make Key implement that one only when being used from a Filesystem ?

**Comment by PaulWoitaschek** [comment]
That would restrict the types one can persist only to types one owns. 
What about instead passing a `PathResolver<T>`?

**Comment by digitalbuddha** [comment]
Maybe just precondition check when filesystem is used that the key implements some interface.

**Comment by pavlospt** [comment]
@digitalbuddha That sounds good as well!

**Comment by PaulWoitaschek** [comment]
So one can't use foreign classes like String or Integer as keys? Id prefer to have a resolver class in that case.

**Comment by digitalbuddha** [comment]
Good point. Resolver it is.  Will make it extra param in file system factory.
