### ISSUE TITLE
Add FileSystemRecordPersister to RecordPersisterFactory

### ISSUE THREAD

**Issue by digitalbuddha** [NYTimes/Store#139]
please add the other Persister implementation to the factory. Additionally rename the Factory to `FileSystemPersisterFactory` and add `FileSystemPersister` to it as well

**Comment by digitalbuddha** [comment]
@pavlospt feel free to take this up

**Comment by pavlospt** [comment]
@digitalbuddha The `FileSystemPersister` does not implement `RecordProvider` though. I can add the relative Factories, but do we want to keep only one implementation or two different ones, with the only difference to be the implementation of the `RecordProvider` ?

**Comment by pavlospt** [comment]
Tracked on #140

**Comment by digitalbuddha** [comment]
@pavlospt will be pushed to snapshot when this finished https://travis-ci.org/NYTimes/Store/builds/204752233
