### ISSUE TITLE
Store.clear() doesn't work as expected

### ISSUE THREAD

**Issue by digitalbuddha** [NYTimes/Store#142]
When a Store's `Persister` is `Clearable` a call to store.clear() does not work as expected.

Expected behavior:
`store.clear()` will call `persister.clear(key)` for any `key` that was ever saved through the store.

Actual Behavior: 
`store.clear()` will call `persister.clear(key)` for only the keys that are currently cached in memory.

The problem is that there is no good way to know what `keys` the user supplied `persister` is using.  

Need to find  a clever solution.

**Comment by pavlospt** [comment]
@digitalbuddha We could say that, we iterate throuh the given root FileSystem and for a given PathResolver add a new method called canResolve(filename). If so then delete the persisted file!

**Comment by PaulWoitaschek** [comment]
The knowledge about which keys are persisted in the persister is only in the persiter.

So what about extending the `Clearable` interface with a `clear()` method and let the persister handle it themselfes?

**Comment by pavlospt** [comment]
@PaulWoitaschek That's what I mean. Thanks for describing it even better!

**Comment by digitalbuddha** [comment]
Yup that works more or less.  The built in `FileSystem` needs an implementation though.  I'm thinking of using https://github.com/square/tape to store all the files names in persistent queues that can then be retrieved for when clear is called.

**Comment by pavlospt** [comment]
@digitalbuddha Since the FileSystem has access to its root, is there a need for another Library?

**Comment by digitalbuddha** [comment]
It becomes complicated if multiple stores are sharing same file system.  We would need to either introduce a better hierarchy to the folder names or use prefixes and traversal. Alternatively we can for each store keep the path names of all elements in a different file.

**Comment by pavlospt** [comment]
@digitalbuddha Isn't it though, the problem of the developer to keep a distinct folder for each Store?

**Comment by digitalbuddha** [comment]
Currently that requirement doesn't exist, for example our app uses only 1 file system for all stores. I need to give this some  thought as I feel like the clearAll should be an implementation detail of the `FileSystemPersister` that it should be able to handle.  Thanks for helping discuss :-)

**Comment by pavlospt** [comment]
@digitalbuddha just a tip here if it helps, I started an approach by letting PathResolver tell me if a File name is resolvable by it. So in the case it was and because a FileSystemPersister already knows about the PathResolver, it could delete the appropriate File. In that case every Store can delete its own Files in case you call a `.clear()` on its Persister.

**Comment by digitalbuddha** [comment]
oh interesting!  something like that can work, I still worry about traversing every file to find the proper ones.

**Comment by pavlospt** [comment]
FileSystem already can list them for you I guess. It has a `.list()` method.

**Comment by digitalbuddha** [comment]
Feel free to take a stab at a PR, if not I should have time later in the week to play with it.

**Comment by pavlospt** [comment]
Tried to start it, but dropped it due to work. Will re-try later in the evening!

**Comment by pavlospt** [comment]
Did not have the time to make any progress on this, if anyone wants to take it off and discuss it further, would be more than happy to help!

**Comment by digitalbuddha** [comment]
Will take a stab in few days.

**Comment by PaulWoitaschek** [comment]
Any progress on this?

**Comment by PaulWoitaschek** [comment]
What is wrong with just distinct FileSystems for distinct Stores and data?

**Comment by digitalbuddha** [comment]
Nope no progress yet but still on my queue. I do not think that it should be a requirement to have distinct file system for each store.  That makes cleanup on something like logout a lil more complicated to manage.    We just need to find a nice strucuture to how we save to FileSystem so that we can have some sort of folder structure supported.  One idea was to pass the name of the store, md5 that and make it a folder which would allow clearing of a particular Store's folder.  I got some free time this weekend to figure things out :-)  thanks for checking in

**Comment by pavlospt** [comment]
@digitalbuddha If you md5 the Store's name, then you are overriding the FileSystem's default name that the user chose.

**Comment by digitalbuddha** [comment]
I now understand why okhttp gives user very little control over the Cache :-)

**Comment by PaulWoitaschek** [comment]
Feel free to make experiences and breaking changes :D

**Comment by digitalbuddha** [comment]
We're going to fix this an elegant way by maintaining list of keys on disk, when a  store comes back we can reinflate the list and be ready to clear particular keys on disk.

**Comment by ZacSweers** [comment]
Is this going to make it into 3.0?

**Comment by digitalbuddha** [comment]
Rather than hacking a solution together we have introduced SourceAllPersister which allows you to make to use barcodes with new Barcode(category,value) and then do persister.readAll(category) or persister.deleteAll(category).  We will be adding an example to the sample projects shortly.
