### ISSUE TITLE
Translate docs to Russian and Chinese 

### ISSUE THREAD

**Issue by digitalbuddha** [NYTimes/Store#145]
Our two largest non English user bases seem to be China and Russia, it would be nice to have translated documentation.

**Comment by maksim-m** [comment]
Do you mean README file? As a Russian native speaker I can help with that.

**Comment by digitalbuddha** [comment]
Yes Readme ideally  the recipes that are in the wiki as well.  Thank you for thinking to contribute!

**Comment by PaulWoitaschek** [comment]
Maybe a naive question but don't all devs speak English? Never seen any German class names so far.

**Comment by digitalbuddha** [comment]
Yup! Most code is in English. Documentation is not the same. For example android docs are localized.  I actually got the idea from OkBuck repo which had Chinese translations for readme/wiki

**Comment by stellaaaaa** [comment]
Hi as a Chinese native speaker I think I can help with that!

**Comment by vohsalab** [comment]
@digitalbuddha  I'm going to translate recipes to Russian.

**Comment by digitalbuddha** [comment]
Thank you good sir!
