### ISSUE TITLE
Why fetch is called every time when getting datas?

### ISSUE THREAD

**Issue by tsaisean** [NYTimes/Store#147]
I'm using `get` method, but `fetch` still get called every time.
I don't know the cache is working or not? 🤔 

```
@Override
protected void onResume() {
    super.onResume();
    Log.d(TAG, "onResume");

    loadPosts();
}
```

```
public void loadPosts() {
    Log.d(TAG, "[loadPosts] start");

    BarCode awwRequest = new BarCode(RedditData.class.getSimpleName(), "aww");

    Log.d(TAG, "[loadPosts] Call provideRedditStore get with key \"aww\"");

    provideRedditStore()
            .get(awwRequest)
            .subscribeOn(Schedulers.io())
            .observeOn(AndroidSchedulers.mainThread())
            .subscribe(new Subscriber<Integer>() {
                @Override
                public void onCompleted() {
                    Log.d(TAG, "[onCompleted]");
                }

                @Override
                public void onError(Throwable e) {

                }

                @Override
                public void onNext(Integer posts) {
                    Log.d(TAG, "[onNext] get " + posts);
                }
            });
}
```

```
private int i = 1;
private Store<Integer, BarCode> provideRedditStore() {
    return StoreBuilder.<Integer>barcode()
            .fetcher(new Fetcher<Integer, BarCode>() {
                @Nonnull
                @Override
                public Observable<Integer> fetch(@Nonnull BarCode barCode) {
                    try {
                        Thread.sleep(5000);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                    int current_i = StoreActivity.this.i++;
                    Log.d(TAG, "[fetch] return " + current_i);
                    return Observable.just(current_i);
                }
            })
            .open();
}
```

**Comment by pavlospt** [comment]
@tsaisean Can you also please post the `get` part of your code?

**Comment by tsaisean** [comment]
@pavlospt Updated.

**Comment by pavlospt** [comment]
@tsaisean And what version are you using?

**Comment by tsaisean** [comment]
@pavlospt I'm using the sample inside the **Store** project. "Store/app/src/"

**Comment by pavlospt** [comment]
@tsaisean Did you delete the persister or something like that? The first time it is supposed to request from Network due to a cache miss, but the second time it will hit your cache.

**Comment by pavlospt** [comment]
![screen shot 2017-03-07 at 11 49 22](https://cloud.githubusercontent.com/assets/1070871/23650862/439f2b20-032c-11e7-8857-f9a35fb023d5.png)

It caches as expected. How did you check that it doesn't work on your case?

**Comment by digitalbuddha** [comment]
Hi thank you for submission but we have to trouble reproducing problem. Could you include a failing test case that shows network getting hit on multiple calls.

**Comment by tsaisean** [comment]
@pavlospt @digitalbuddha 
I'm using **StoreActivity**, not **PersistingStoreActivity**.
`/Store/app/src/main/java/com/nytimes/android/sample/activity/StoreActivity.java`
I intended to use memory cache only, and no disk cache.

**Comment by digitalbuddha** [comment]
Sure but when you say network is being called how do you see that?

**Comment by tsaisean** [comment]
I didn't say network. I modify the sample a bit. 😄

```
private Store<Integer, BarCode> provideRedditStore() {
    return StoreBuilder.<Integer>barcode()
            .fetcher(new Fetcher<Integer, BarCode>() {
                @Nonnull
                @Override
                public Observable<Integer> fetch(@Nonnull BarCode barCode) {
                    try {
                        Thread.sleep(5000);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                    return Observable.just(5);
                }
            })
            .open();
}
```

**Comment by digitalbuddha** [comment]
Pls show me fetch being executed multiple times

**Comment by tsaisean** [comment]
![image](https://cloud.githubusercontent.com/assets/4138501/23658214/9a3c88b0-037c-11e7-822e-34b4347f39b9.png)

Still waiting 5 secs for 2nd load since `fetch` is invoked again.

**Comment by digitalbuddha** [comment]
Do me a favor. Make fetch return i++ so value changes each time it is executed. I'll  be at work in hour and can see what's up then.

**Comment by pavlospt** [comment]
@tsaisean When do you call the `Store.get()` method? As I see from your screenshot seems like you are sending the app on background and call `.get()` in `onResume()` ?

**Comment by tsaisean** [comment]
@pavlospt 
Yes, I expected to get the value from memory cache directly for the 2nd `onResume`.

**Comment by tsaisean** [comment]
@digitalbuddha 
```
03-07 08:44:26.743 27674-27674/com.nytimes.android.sample D/StoreActivity: onResume
03-07 08:44:26.743 27674-27674/com.nytimes.android.sample D/StoreActivity: [loadPosts] start
03-07 08:44:26.743 27674-27674/com.nytimes.android.sample D/StoreActivity: [loadPosts] Call provideRedditStore get with key "aww"
03-07 08:44:31.817 27674-27751/com.nytimes.android.sample D/StoreActivity: [fetch] return 1
03-07 08:44:31.823 27674-27674/com.nytimes.android.sample D/StoreActivity: [onNext] get 1
03-07 08:44:31.823 27674-27674/com.nytimes.android.sample D/StoreActivity: [onCompleted]
03-07 08:44:41.555 27674-27674/com.nytimes.android.sample D/StoreActivity: onResume
03-07 08:44:41.555 27674-27674/com.nytimes.android.sample D/StoreActivity: [loadPosts] start
03-07 08:44:41.555 27674-27674/com.nytimes.android.sample D/StoreActivity: [loadPosts] Call provideRedditStore get with key "aww"
03-07 08:44:46.556 27674-27751/com.nytimes.android.sample D/StoreActivity: [fetch] return 2
03-07 08:44:46.557 27674-27674/com.nytimes.android.sample D/StoreActivity: [onNext] get 2
03-07 08:44:46.557 27674-27674/com.nytimes.android.sample D/StoreActivity: [onCompleted]
```

**Comment by digitalbuddha** [comment]
Can you push your code to github I'll look in a few.

**Comment by pavlospt** [comment]
@tsaisean I think I know why this is happening! Well, since you are using the sample app, it means that each time you call `loadPosts()` you create a new `Store` object. What this does is create it from scratch and then give it back so you can call `.get()`. Even if you added a memory caching there, it would still not work. 

What you need to do is: 1) Create a class variable and instantiate `Store`. When you are going to use it, check if it is already null and instantiate it. 2) Use the class variable to call `.get()` on instead of the method.

**Comment by tsaisean** [comment]
@pavlospt You are right! I'm blind. 😞 

Thanks for your help! @pavlospt and @digitalbuddha 
Very appreciated!! 🙂

**Comment by digitalbuddha** [comment]
https://github.com/NYTimes/Store/issues/148 sample needs fixing
