### ISSUE TITLE
MO no op MO problems 

### ISSUE THREAD

**Issue by digitalbuddha** [NYTimes/Store#150]
#149 raises another interesting issue. If the mem cache is less than a minute the in flight denouncer also needs to be adjusted. Secondly the no op persister needs to be migrated to use a guava cache which has same policy as mem cache.

**Comment by pavlospt** [comment]
@digitalbuddha You can though have a NoopPersister without having to add a memcache, right? What would happen in such a case?

**Comment by digitalbuddha** [comment]
Mem Cache is necessary there is no way to skip.

**Comment by digitalbuddha** [comment]
The memory cache is actually used for some of the inflight blocking logic
