### ISSUE TITLE
Using the persister

### ISSUE THREAD

**Issue by PaulWoitaschek** [NYTimes/Store#156]
I am still not using a persister as there are still some things I don't get:

How can you use retrofit with the `FileSystemPersister`? Do you have a `CallAdapter` for BufferedSource or how do you do it?

Also if I understand correctly it does not operate with stale and clear functionality. Shouldn't it implement `RecordProvider` and `Clearable`?

**Comment by pavlospt** [comment]
What we do is that we use `.share()` on our observable and then use that Observable so that we can map it to a BufferedSource that will then be written on the disk. 

e.g.:

```java
Gson gson = new Gson();
ByteArrayInputStream is = new ByteArrayInputStream(gson.toJson(object).getBytes(UTF_8));
BufferedSource bufferedSource = Okio.buffer(Okio.source(is));
return bufferedSource;
```

**Comment by PaulWoitaschek** [comment]
But that's terrible inefficient. You let Gson map the data to a pojo for retrofit. Then the persister will write it to a Buffered source and write it to disk. Then the persiter will read it and map it through Gson to a pojo.

That's a chain of:
`network -> pojo -> bufferedSource -> file -> bufferedSource -> pojo`

**Comment by pavlospt** [comment]
That is just our way because we want to operate on the POJO before converting it to a BufferedSource. You could just skip that part and have your network write directly on a BufferedSource.

**Comment by PaulWoitaschek** [comment]
And how can I do that using retrofit?

**Comment by pavlospt** [comment]
@PaulWoitaschek Just return BufferedSource instead of returning a POJO on the method that you are using in your Fetcher.

**Comment by PaulWoitaschek** [comment]
Retrofit can't return `BufferedSource`. That's why I was asking for a call adapter.

**Comment by pavlospt** [comment]
@PaulWoitaschek I have used it before with just adding `Observable<BufferedSource>` and it worked..

**Comment by digitalbuddha** [comment]
Hi @PaulWoitaschek thank you for questions. We do in fact use a `BufferedSourceConverterFactory` with retrofit. 
```
public final class BufferedSourceConverterFactory extends Converter.Factory {
  @Override
  public Converter<ResponseBody, ?> responseBodyConverter(Type type, Annotation[] annotations,
                                                          Retrofit retrofit) {
    if (!BufferedSource.class.equals(type)) {
      return null;
    }
    return new Converter<ResponseBody, BufferedSource>() {
      @Override public BufferedSource convert(ResponseBody value) throws IOException {
        return value.source();
      }
    };
  }
}
```
As for the Record/Clearable stuff we do have another Persister Impl that has both, I can pr it into the Store lib if you'd like.
```
public final class FileSystemRecordClearingPersister<Key> implements Persister<BufferedSource, Key>,
        RecordProvider<Key>,
        Clearable<Key> {
    private final FSReader<Key> fileReader;
    private final FSWriter<Key> fileWriter;
    private final FileSystem fileSystem;
    private final PathResolver<Key> pathResolver;
    private final long expirationDuration;
    @Nonnull
    private final TimeUnit expirationUnit;

    private FileSystemRecordClearingPersister(FileSystem fileSystem, PathResolver<Key> pathResolver,
                                              long expirationDuration,
                                              @Nonnull TimeUnit expirationUnit) {
        this.fileSystem = fileSystem;
        this.pathResolver = pathResolver;
        this.expirationDuration = expirationDuration;
        this.expirationUnit = expirationUnit;
        this.fileReader = new FSReader<>(fileSystem, pathResolver);
        this.fileWriter = new FSWriter<>(fileSystem, pathResolver);
    }

    @Nonnull
    public static <T> FileSystemRecordClearingPersister<T> create(FileSystem fileSystem,
                                                                  PathResolver<T> pathResolver,
                                                                  long expirationDuration,
                                                                  @Nonnull TimeUnit expirationUnit) {
        if (fileSystem == null) {
            throw new IllegalArgumentException("root file cannot be null.");
        } else {
            return new FileSystemRecordClearingPersister<>(fileSystem, pathResolver,
                    expirationDuration, expirationUnit);
        }
    }

    @Nonnull
    public RecordState getRecordState(@Nonnull Key key) {
        return this.fileSystem.getRecordState(this.expirationUnit,
                this.expirationDuration,
                this.pathResolver.resolve(key));
    }

    @Nonnull
    public Observable<BufferedSource> read(@Nonnull Key key) {
        return this.fileReader.read(key);
    }

    @Nonnull
    public Observable<Boolean> write(@Nonnull Key key, @Nonnull BufferedSource bufferedSource) {
        return this.fileWriter.write(key, bufferedSource);
    }

    @Override
    public void clear(@Nonnull Key key) {
        try {
            fileSystem.deleteAll(pathResolver.resolve(key));
        } catch (IOException e) {
            Log.e("don't worry about it", ":-)");
        }
    }
}
```

The store will absolutely respect streaming from network to FS without having to worry about inflating and deflating Pojos unnecessarily. :-D
Not sure if I answered all your questions, please don't hesitate to follow up if you have any other questions!

**Comment by digitalbuddha** [comment]
Fyi when registering the above adapter, order does matter this works:
```
Retrofit.Builder retrofitBuilder = new Retrofit.Builder()
                .client(client)
                .addConverterFactory(new ToStringConverterFactory())
                .addConverterFactory(new BufferedSourceConverterFactory())
                .addConverterFactory(GsonConverterFactory.create(gson))
                .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
```

**Comment by PaulWoitaschek** [comment]
Great! Why not adding that functionallity to the `FileSystemPersister` directly? Also this does not handle the `clearAll` case, right?

**Comment by digitalbuddha** [comment]
Breaking change, open source is harder than I thought :-) 

Doesn't handle `clearAll`.  I'm open to a PR that would have `clear()` delete everything in the root folder allowing you to use a seperate file system for each store...  I can't think of a better solution for the time being.

**Comment by hwt88** [comment]
How can i change Persister<BufferedSource,T> to Persister<POJO,T> in FileSystemPersister ? Beacause i don't want to change my Retrofit interface to return Observable<BufferedSource> !

**Comment by digitalbuddha** [comment]
You would need to either implement your own persister or return observable
of a BufferedSource from retrofit. If you want the second option I can post
a converter to use

**Comment by hwt88** [comment]
@PaulWoitaschek Ok , so post the converter ! Thanks

**Comment by digitalbuddha** [comment]
```
public final class BufferedSourceConverterFactory extends Converter.Factory {
  @Override
  public Converter<ResponseBody, ?> responseBodyConverter(Type type, Annotation[] annotations,
                                                          Retrofit retrofit) {
    if (!BufferedSource.class.equals(type)) {
      return null;
    }
    return new Converter<ResponseBody, BufferedSource>() {
      @Override public BufferedSource convert(ResponseBody value) throws IOException {
        return value.source();
      }
    };
  }
}
```
