### ISSUE TITLE
RxJava2 Remaining Tasks

### ISSUE THREAD

**Issue by digitalbuddha** [NYTimes/Store#167]
Port to Rxjava2 is a less trivial than initially imagined. to close #155 we still need to do 
- [ ] create branch 1.x
- [x] change package to com.nytimes.android.external.store2
- [x] return single/maybe where appropriate.  #185

**Comment by PaulWoitaschek** [comment]
Why the interop? Why not just use the rxjava interop library?

**Comment by digitalbuddha** [comment]
It would mean you'd need to either make a wrapper for each Store or use the interop every time you call any of the legacy stores.  Since one of our stores has 50+ subscribers that vary in which public api they are subscribing to, it felt like a nice convenience.

**Comment by digitalbuddha** [comment]
Talked at meeting, won't need interop. Also we are not going to wait to convert internally. So really all that is needed is the creation of the 1.x branch, package rename and release. We will then support both the 1.x and 2.x branch until we can convert internally.

**Comment by mradzinski** [comment]
@digitalbuddha I'm still up for the last task on that list. I'll start working on it as soon as 2.x branch becomes available and I get some free time from work.

**Comment by digitalbuddha** [comment]
Anyone want to be first victim and try the new artifacts? I just pushed first snapshots
https://oss.sonatype.org/content/repositories/snapshots/com/nytimes/android/


@mradzinski please see branch feature/rx2, feel free to create an issue and start on single/maybe stuff.  Not sure where it fits perfectly but would be happy to discuss.

**Comment by mradzinski** [comment]
@digitalbuddha I forked the repo and started working on a new branch based on the feature/rx2 one. I'll make a PR as soon as I'm done with it so we can merge it to rx2 here 😉

**Comment by digitalbuddha** [comment]
It would be helpful if you can make issues expiring what you will do as well. Thank you good sir!

**Comment by mradzinski** [comment]
Just a small update. I've been extremely busy with some projects at work and haven't had a chance of working on this. I'll attempt to tackle the single/maybe task next week, but if anyone wants to start working on it please be my guest.
