### ISSUE TITLE
Failed to sync Gradle project

### ISSUE THREAD

**Issue by kien92** [NYTimes/Store#168]
Error:Could not GET 'https://oss.sonatype.org/service/local/staging/deploy/maven2/com/android/support/recyclerview-v7/25.1.1/recyclerview-v7-25.1.1.pom'. Received status code 401 from server: Unauthorized
<a href="toggle.offline.mode">Enable Gradle 'offline mode' and sync project</a>

Please help?
Thanks

**Comment by PaulWoitaschek** [comment]
This is completely unrelated to this library. Google or ask at stackoverflow
