### ISSUE TITLE
Typo in the english wiki

### ISSUE THREAD

**Issue by oldergod** [NYTimes/Store#169]
There seems to me missing spaces for many `###titles`.

![image](https://cloud.githubusercontent.com/assets/1767669/24250201/634539c0-1019-11e7-8759-1ea52d0b9155.png)

![image](https://cloud.githubusercontent.com/assets/1767669/24250210/67e7f6ac-1019-11e7-81a4-5400c418343e.png)

etc.

**Comment by digitalbuddha** [comment]
Fixed. Thank you. lmk if I missed any
