### ISSUE TITLE
Get all the items of a given type?

### ISSUE THREAD

**Issue by riclage** [NYTimes/Store#172]
I'm currently only using the filesystem lib to persist data locally but I'm struggling to find a convenient way to fetch all items of a given type from my cache.

As far as I understood, currently I would need to keep another object in cache with the reference to objects I want returned and make sure I keep this parent object updated.

It seems this could be improved by making the "type" a folder in the filesystem by changing the `pathForBarcode()` method to something like:

```
    @Nonnull
    static String pathForBarcode(@Nonnull BarCode barCode) {
        return barCode.getType() + "\" + barCode.getKey();
    }

```

Then we could use the `Filesystem.list(barCode.getType())` method to get all the files from that folder and read them back to the requester.

Does that make sense? Is that something you would consider looking into? I could try to make a PR with that change.

**Comment by pavlospt** [comment]
I think that this was not something that Store was designed for. Maybe something like a plugin could work in this case, in the sense of making Store extensible.

**Comment by digitalbuddha** [comment]
I would be open to a PR that creates an additional override to filesystem read which takes a folder and path. We can then change the pathForBarcode while still allowing other users to keep data flat. Thank you for using library.

**Comment by riclage** [comment]
> which takes a folder and path

Taking a folder and a path won't solve the issue since the `path` will still point to a specific item, no? Why not just use `list()` which is already present and get all files of a given `type` folder?

**Comment by digitalbuddha** [comment]
Misread your original comment. Changing the `pathForBarcode` method without making any change to the file system makes sense.

**Comment by digitalbuddha** [comment]
Hey could you tell me what you're using for the File System. Which version and Persister specifically.  I'll make the change today.

**Comment by riclage** [comment]
Hey, thanks!

I'm using only the filesystem lib version 2.0.3 with `SourcePersisterFactory.create(context.getCacheDir())` to create my `Persister<BufferedSource, BarCode>`. 

What I'm looking for is to have something like a `persister.readAll(BarCode.type())` method to return `Observable<List<Raw>>`.

**Comment by dhenry** [comment]
Hey is this still being actively worked on?

**Comment by digitalbuddha** [comment]
So sorry for delay. It is. We needed to make a strategy that would not
introduce breaking changes. Will have something in this week.

**Comment by dhenry** [comment]
No worries, thanks for the update

**Comment by digitalbuddha** [comment]
Sorry this keep stalling, we have a pr #194 that has the fix but had a messy rebase, awaiting a cleanup of that branch and then we will be good to go.  In addition to get all items for a given type we have also implemented delete all items for a given type.

**Comment by dhenry** [comment]
Great, looking forward to it 👍

**Comment by digitalbuddha** [comment]
Pr is open, waiting for developer to fix messy merge and then it'll be in
next release ☺️

**Comment by dhenry** [comment]
Hey, do you have an update on this?

**Comment by digitalbuddha** [comment]
Pr was merged last night. I'll add documentation for use this weekend.

**Comment by dhenry** [comment]
👏  Thanks thats great news!
