### ISSUE TITLE
Adopt major Versioning naming similar to square libs 

### ISSUE THREAD

**Issue by digitalbuddha** [NYTimes/Store#174]
We are approaching the release of Store built with Rxjava2.  Since the current version of Store is 2+ we will follow a pattern similar to okhttp/retrofit  when naming artifacts 

http://jakewharton.com/java-interoperability-policy-for-major-version-updates/

com.nytimes.android.store3 will be the package that all artifacts share 

We will then have .store3:3.0.0 as the first release with Rxjava2

Any breaking changes will warrant a store4 release with similar version numbers. 

Similar there will be middleware3:3.0.0 as well as the file system.

Still undecided about what to do with cache artifact as there are no breaking changes since cache was a port from guava. Might move to its own repo 

Suggestions welcome if this does not work for someone.

**Comment by maksim-m** [comment]
> Still undecided about what to do with cache artifact as there are no breaking changes

I think, it must be the same version for all artifacts so that users can easily update Store dependencies.

**Comment by digitalbuddha** [comment]
We have started to convert our internal code base to RxJava2, as part of this conversion we will be doing a stable release of Store3 which will be built on RxJava2.  This also means that we will be deprecating Store(1).   Stay tuned :-)

**Comment by pavlospt** [comment]
@digitalbuddha What does deprecation, effectively mean?

**Comment by digitalbuddha** [comment]
@pavlospt one of the pain points we have now is that any changes to store built on RxJava1 means we also need to update the rx2 branch. Deprecation would mean that we would make Store3 (RxJava2 version) the primary develop branch and would officially stop new feature development on the Store (built with RxJava1) artifacts.  If a dire bug exists we would fix it but that would be the extent of support.  The community is free to continue development if they would like but I don't think it is sustainable as RxJava is getting deprecated next month as well.  If you would like you can use Store3 with the RxJava Interop Library https://github.com/akarnokd/RxJava2Interop which will allow you to convert from an RxJava2 Observable to an RxJava Observable (but really I encourage you to join us in moving forward to a supported version of RxJava & Store).  There are performance as well as usability improvements already in the Rx2 branch such as the use of `Single` and `Maybe` where appropriate.

**Comment by pavlospt** [comment]
@digitalbuddha Thanks for the insights! I suppose it is time for everyone to move to RxJava 2 :P
