### ISSUE TITLE
NotifySubscriber SideEffect causes StackOverflows on Samsung tablets

### ISSUE THREAD

**Issue by digitalbuddha** [NYTimes/Store#180]
We started seeing StackOverflowExceptions coming from Samsung tablets running 4.4.2 

Diving into the issue it seems like it is coming from this area of code
```
Observable<Parsed> response(@Nonnull final Key key) {
        return fetcher()
            .fetch(key)
            .flatMap(new Func1<Raw, Observable<Parsed>>() {
                @Override
                public Observable<Parsed> call(Raw raw) {
                    return persister().write(key, raw)
                        .flatMap(new Func1<Boolean, Observable<Parsed>>() {
                            @Override
                            public Observable<Parsed> call(Boolean aBoolean) {
                                return readDisk(key);
                            }
                        });
                }
            })
            .onErrorResumeNext(new Func1<Throwable, Observable<? extends Parsed>>() {
                @Override
                public Observable<? extends Parsed> call(Throwable throwable) {
                    if (stalePolicy == StalePolicy.NETWORK_BEFORE_STALE) {
                        return readDisk(key);
                    }
                    return Observable.error(throwable);
                }
            })
            .doOnNext(new Action1<Parsed>() {
                @Override
                public void call(Parsed data) {
                    notifySubscribers(data);
                }
            })
            .doOnTerminate(new Action0() {
                @Override
                public void call() {
                    inFlightRequests.invalidate(key);
                }
            })
            .cache();
    }

    void notifySubscribers(Parsed data) {
        subject.onNext(data);
    }
```

The issue is that notifySubscribers is coming from a `doOnNext` (Side effect) which means that anyone listening to `store.stream()` gets a stack of all the operators that came from the network response/disk read/disk write flow.  We need to figure out a way to rewrite this code in a manner that will have `notifySubscribers` not be called as part of this stream but instead as its own stream.  

Some ideas we floated around was creating a key of keys and then having a background thread periodically check the queue to push values through the stream subject. 

Other suggestions of how to handle are greatly appreciated.

**Comment by pavlospt** [comment]
What if you `.share()` this stream and call `.doOnNext()` on a new one created from the shared ?

**Comment by digitalbuddha** [comment]
I'm not sure if that would be sufficient as the shared stream still will be very long. Its feels more like we want to squash the observable into something smaller or somehow translate it somewhere else.  Again this is very edge case on 2 samsung tablets that seem to have mucked with stack size
