### ISSUE TITLE
Add Lambdas

### ISSUE THREAD

**Issue by digitalbuddha** [NYTimes/Store#183]
Since the desugar tool will be a part of gradle 2.5 I think it's time to add retrolambda and start simplifying `RealInternalStore` among other classes.  

We are open to an external contribution for this.

**Comment by pavlospt** [comment]
If anyone starts this, please mention it here, so that we can avoid double wasted work :)

**Comment by Fitzpasd** [comment]
I'd like to tackle this.  The ask is to introduce RetroLambda in anticipation of moving to the desugar tool when that's ready?

**Comment by PaulWoitaschek** [comment]
Make sure not to make use of try with resources as desugar does not support that yet but retrolambda does.

**Comment by Fitzpasd** [comment]
Sure.  We've recently done this in work, only using the lamda part of RetroLambda (no try-with-resource, default methods, etc.)

**Comment by digitalbuddha** [comment]
Sounds good please take it on. Don't forget about converting tests too please

**Comment by ZacSweers** [comment]
I think the idea with desugar would be that you should write your library in java 8 and ship java 8 code, then desugar would run during the consuming app

**Comment by digitalbuddha** [comment]
I believe we still need to convert a few modules before closing
