### ISSUE TITLE
can i update other key in a store after fetcher?

### ISSUE THREAD

**Issue by stat0s2p** [NYTimes/Store#184]
Dear,
i want use this lib in a RecyclerView adapter for very long list.
for example i have api /books?skip=10&limit=10 return 10 items，but the adapter request one item  per time on onBindViewHolder(holder,position).if i use it directly,it will request network 10 times.
i think is effective if i can update 9 other items on store fetch callback.
is any api can do that？thank you.

**Comment by pavlospt** [comment]
@stat0s2p Why do you need onBindViewHolder to make the network fetch?

**Comment by stat0s2p** [comment]
@pavlospt
Thank you for reply.Well,may be I do network fetch on ScrollListener is better.Just like YouTube,My app user can free to scroll hundred of records.at first,I want use the Store library as data source solve the memory problem.My WEB API request one more items on one request,I find it is hardly work with RecyclerView and my WEB API.
I think it is helpful if it offer a store.set(key,object) API,then I can update other keys after the network fetch.

**Comment by digitalbuddha** [comment]
You can make a custom persister. Within this custom persister you can normalize your results in any manner you choose. Now you have control over how data is saved and retrieved. You can in theory make 1 store call then update ten files. Next you can make a store call to get each of those results separately.

**Comment by stat0s2p** [comment]
@digitalbuddha  Yes,I think instance a NoopPersister pass to StoreBuilder and use the write method set cache manually.thank you for your help.
