### ISSUE TITLE
Using persister without fetcher

### ISSUE THREAD

**Issue by sahibjaspal** [NYTimes/Store#187]
I'm having difficulty with using a persister without a fetcher.

Let's say that I already have an object that I want to store (I don't need a network call to grab it),

ItemToStore itemToStore = new ItemToStore();

How can I use the persister without using a fetcher?

**Comment by digitalbuddha** [comment]
While this is outside of the typical use case, you can make a Fetcher that takes as input ItemToStore and returns the same item back from fetcher.

**Comment by sahibjaspal** [comment]
Thanks!
