### ISSUE TITLE
A typo in Readme?

### ISSUE THREAD

**Issue by AlexeyGorovoy** [NYTimes/Store#197]
There's this code in the readme file under "Creating a Store" section:
```
        Store<ArticleAsset, Integer> store = StoreBuilder.<ArticleAsset,Integer>key()
                .fetcher(articleId -> api.getArticle(articleId))  //OkHttp responseBody.source()
                .open();
```

I'm asking about the second line, parameter `articleId` here has ArticleAsset type isn't it? And the method api.getArticle(..) returns Integer. 

Shouldn't it be like this instead:
```
        Store<ArticleAsset, Integer> store = StoreBuilder.<Integer,ArticleAsset>key()
                .fetcher(articleId -> api.getArticle(articleId))  //OkHttp responseBody.source()
                .open();
```

**Comment by leighsn** [comment]
yup! just some copy pasta, mind opening a PR to fix? I think we can simplify with `StoreBuilder.<>key()` I believe.
