### ISSUE TITLE
Build with Java 8 on 2.0.5-SNAPSHOT breaks compatibility

### ISSUE THREAD

**Issue by pavlospt** [NYTimes/Store#204]
Hello everyone, 

We need to use the 2.0.5-SNAPSHOT version because of a crucial fix, but it currently is impossible due to it being built with Java 8. 

Is there any chance to not build it with Java 8 or a workaround for including on non-java8-targeting projects ?

Best

**Comment by pavlospt** [comment]
Update: This was introduced in #188

**Comment by digitalbuddha** [comment]
Any reason you cannot target 1.8?

**Comment by pavlospt** [comment]
Because we would need to add Retrolambda as well if i am not wrong, which would also increase our compile time. 

Generally I believe that there are a lot of projects that might be using Store and can not target Java 8 yet. It seems a bit strange to introduce such a breaking change, just for the Lambdas. Let us know if there is something else behind it :)

**Comment by digitalbuddha** [comment]
Retro lambda will convert the lambdas to equivalent  byte code to anonymous
classes. AFAIK you only need to set your compatability to 1.8 you do not
need to include retro lambda

**Comment by pavlospt** [comment]
Adding compileOptions with source and target compatibility is not enough...

**Comment by digitalbuddha** [comment]
Sorry for hassle. I'm away for few days I will absolutely fix this when
back. It should work not sure what we misconfigured

**Comment by digitalbuddha** [comment]
Hi Pavlos it was a misconfiguration, we need to apply retro lambda to all modules. I'll see if someone at work can fix it today. Thank you so much for reporting!

**Comment by pavlospt** [comment]
Great, keep me posted :)

**Comment by pavlospt** [comment]
There is something really awkward going on with this issue.

If you try to compile the sample app with: 
```gradle
compile project(path: ':store')
compile project(path: ':cache')
compile project(path: ':middleware')
compile project(path: ':filesystem')
```
everything works out great. But if you try to compile it with the Snapshot that it's exactly the same, you can not build the app. I could not have tested earlier, with the Snapshot due to it not being built yet from the merged PR and I thought that it worked.

Non working dependency
```gradle
compile 'com.nytimes.android:store:2.0.5-SNAPSHOT'
compile'com.nytimes.android:cache:2.0.5-SNAPSHOT'
compile'com.nytimes.android:middleware:2.0.5-SNAPSHOT'
compile 'com.nytimes.android:filesystem:2.0.5-SNAPSHOT'
```

@digitalbuddha @brianPlummer Will try to Google it a little bit more. Let me know if you can think of something else. 

P.S.: Shall we also re open the issue in case someone else is looking into it ?

**Comment by digitalbuddha** [comment]
Sure reopen worst case I'm home Saturday and will take a look ☺️

**Comment by oldergod** [comment]
I had no problem building the sample app.

![image](https://cloud.githubusercontent.com/assets/1767669/26147055/47ead146-3b2d-11e7-8a93-f0baaed640e7.png)

`./gradlew clean :app:build`

![image](https://cloud.githubusercontent.com/assets/1767669/26147112/786f3622-3b2d-11e7-8cff-249c50962a8d.png)

@pavlospt is there something else I need to change when building it?

**Comment by pavlospt** [comment]
@oldergod Did you try running it ?

**Comment by oldergod** [comment]
@pavlospt yes, working fine.

**Comment by pavlospt** [comment]
@oldergod I am trying the same sample app and the same build command and it does not work. How is that possible :P ?

**Comment by oldergod** [comment]
What error do you have? Any stacktrace to share maybe?

2017-05-17 18:27 GMT+09:00 Pavlos-Petros Tournaris <notifications@github.com

**Comment by pavlospt** [comment]
False alarm eventually. I tried with: 

`./gradlew cleanBuildCache` had no luck either and then I finally deleted all `.gradle/caches` and somehow it worked. 

@digitalbuddha I guess you can close it now. Seems though that everyone that will possibly use the new version, might need to do the same. Might worth being a note in ReadMe or Wiki?

**Comment by digitalbuddha** [comment]
We will tick version up before stable release.
