### ISSUE TITLE
Feature Request: Use Single<T> where appropriate

### ISSUE THREAD

**Issue by PaulWoitaschek** [NYTimes/Store#22]
I'm not sure but it seems to me that for certain operations there are more appropriate reactive base types that would make the API more fluently.

One candidate:
`Store.get(barcode : Barcode) : Observable<T>`
here a `Single<T>` would clearly indicate that its always just a single item that is being emitted.

**Comment by digitalbuddha** [comment]
We went back and forth with this. 
Pro: more clear that only 1 emission
Con: Not all operators are implemented which limits how you can combine multiple stores into a single observable or dealing with long stacktraces when going `toObservable` and back a few times.   

We're not against it but to be honest I don't see much value in Observable over Single.  Maybe as part of the 2.x addition this can be added as well.

**Comment by PaulWoitaschek** [comment]
RxJava 2 has more operators available and is better composable so that sounds like a good idea.

Also it would better match to the RxJava 2 API as its operators directly indicate the outcome too.
All its operators that return a single value return a Single, for example `.toList`.

**Comment by digitalbuddha** [comment]
Something to think about. What happens if fetcher returns a stream? Single won't work for that case...

**Comment by PaulWoitaschek** [comment]
That behavior is currently really undefined.

In response there is:

```java
fetcher()
                .fetch(key)
                .flatMap(new Func1<Raw, Observable<Parsed>>() {
                    @Override
                    public Observable<Parsed> call(Raw raw) {
                        return persister().write(key, raw)
                                .flatMap(new Func1<Boolean, Observable<Parsed>>() {
                                    @Override
                                    public Observable<Parsed> call(Boolean aBoolean) {
                                        return readDisk(key);
                                    }
                                });
                    }
                })
```

For flatMap the order of execution is not guaranteed and there will be a lot of read and writes concurrently without any synchronization. You might end up with `readDisk` results from previous `writeDisk` results or have written older responses first.

So either one handles that properly by using concatMap / switchMap and taking care of order of execution. Or you just define that it's a single value.

**Comment by digitalbuddha** [comment]
Good point. What I was trying to figure out is how to make Store work with something like a websocket.  Back to brainstorming.

**Comment by mradzinski** [comment]
@digitalbuddha, `Single` does have an operator called `toObservable()` which should allow anyone to use  `Observable` operators in case those are needed. Rx recommendations are to use `Single`, `Completable` and `Maybe` when applicable, and I think RxJava2 is promoting that practice as well. I'm with @PaulWoitaschek that this will add clarity to the API.

**Comment by digitalbuddha** [comment]
Makes sense, theres a PR out now to do the conversion to rx2. Once we land that let's start on adding Maybe/SIngle/Completable :-)

**Comment by mradzinski** [comment]
Absolutely. As far as I read the idea is to land the PR this week, right? If so I can try making myself some time during the weekend or beginning of next week to help you guys with this feature request if you want.

**Comment by digitalbuddha** [comment]
Yup idea is this week. I got stuck with some blockers. Hoping to make a solid effort tomorrow/Wednesday
