### ISSUE TITLE
a small mistake in README.md

### ISSUE THREAD

**Issue by nbhaohao** [NYTimes/Store#228]
In README.md , I guess It is a small mistake in this code . 
![barcode](https://user-images.githubusercontent.com/23535619/27091061-9bd4e03e-5091-11e7-9629-cd5863260c49.png)
I think  change ` Store<ArticleAsset, Integer>` to `Store<ArticleAsset, BarCode>`  is right . 
besause StoreBuilder create a Store<ArticleAsset,BarCode>

**Comment by digitalbuddha** [comment]
yup! want to pr a fix?
