### ISSUE TITLE
Change Request: Consider migrating Barcode to a Barcode<T>

### ISSUE THREAD

**Issue by PaulWoitaschek** [NYTimes/Store#23]
I find the BarCode class very limiting, because:

* A String,String key value type rarely matches my key type
* Its not type safe. If you just have a single int as a key you need to remember to set it as the string value of the key and follow that convention. When you need for example an int, the `Integer.parseInt()` makes it even more dangerous

I suggest to replace the BarCode class completely with generics.

Then the sample would just look like:
```java
  private Store<RedditData, String> provideRedditStore() {
    return StoreBuilder.<RedditData, String>builder()
      .fetcher(key -> provideRetrofit().fetchSubreddit(key, "10"))
      .open();
  }

  public void loadPosts() {
    String awwRequest = "aww";
    provideRedditStore()
      .get(awwRequest)
      .flatMap(this::sanitizeData)
      .toList()
      .subscribeOn(Schedulers.io())
      .observeOn(AndroidSchedulers.mainThread())
      .subscribe(this::showPosts, throwable -> {
        Log.e(StoreActivity.class.getSimpleName(), throwable.getMessage(), throwable);
      });
  }
```

**Comment by digitalbuddha** [comment]
Thanks for the suggestion. We actually started down that route and backed off from it.  For one thing the ParsingStoreBuilder used to need 3 generics `<Raw,Parsed,Barcode>`.  Additionally all the user implemented pieces need to carry an additional generic for the barcode.  The thing is that this still doesn't do any type of auto mapping (for example, if your barcode was RequestPOJO, you still need to know which fields need to be read out in the `fetcher` & `persister` and read them in/out yourself).

Internally, we go with a solution of using a gson serializer for any keys that need to contain more than 2 values or want to be differently named.  We then can do something like `Barcode=BarcodeCreator.from(field1,field2,field3)` when creating the barcode and `BarcodeCreator.decode` when using it within each layer to turn back into a particular pojo.

My rational was that try to keep this as simple as possible.  

In theory there's nothing stopping you from creating `MyBarcode<T> extends Barcode` and then casting to the subclass when you need it to read your values. (Just remember that the Barcode is also used as a key within the in-memory cache).

Thank you for suggestion, I'll bring it up at next internal dev meeting and see how team feels about it.

**Comment by PaulWoitaschek** [comment]
Any news on this?

I tried your approach:
> In theory there's nothing stopping you from creating MyBarcode<T> extends Barcode and then casting to the subclass when you need it to read your values. (Just remember that the Barcode is also used as a key within the in-memory cache).
But it's final:

`public final class BarCode implements Serializable`.

Why is it serializable?

**Comment by digitalbuddha** [comment]
Working towards it with code gen. Should be out next week.

**Comment by digitalbuddha** [comment]
I need to give this some more thought, I can't find a solution that does not lead to a triple generic `ParsingStoreBuilder<T,R,V>`  We're open to suggestions of how to handle this.  Maybe there's some generic/casting magic I am not aware of.  I'd also be ok with suppressing a cast exception if it can be localized to a single place.

**Comment by PaulWoitaschek** [comment]
I don't really see the issue here. When using lambdas, the type interference will handle most of the things. As a consumer it looks more like something the library is handling; see the example above.

And the barcode stuff is even more complicated. I am wrapping each Barcode through a moshi adapter and have something like

```
class <T> BarcodeDecoder(adapter:JsonAdapter<T>) {

    fun decode(barcode:BarCode) = adapter.fromJson(barcode.key)

    fun encode(value : T) = BarCode("", adapter.toJson(value))
}
```

Thats quite some pain ;)

**Comment by digitalbuddha** [comment]
Maybe I'm missing something, the store delegates to your fetcher. The fetcher takes a param. The Store needs to know what type to make the param. The only way I see this working is if you pass in a generic to the StoreBuilder with the barcode type. I just need to play with it some more and find a solution that works for you with complicating the simpler use case

**Comment by digitalbuddha** [comment]
Had a bit of a breakthrough.  I just need to settle on what to name things and some cleanup.  Right now I have something that looks like:

```java
Store<JSONArray, Integer> store = new StoreBuilder<JSONArray>()
                .keyAndRawType(Integer.class, String.class)
                .fetcher(new Fetcher<String, Integer>() {
                    @NonNull
                    @Override
                    public Observable<String> fetch(Integer barCode) {
                        return Observable.empty();
                    }
                })
                .parser(new Parser<String, JSONArray>() {
                    @Override
                    public JSONArray call(String s) {
                        return null;
                    }
                })
                .open();
        
        store.get(5).subscribe();
```

The nice part about the change is that it eliminates the `ParsingStoreBuilder`. If there is a particular way you want the above to look let me know.

Bedtime :-)

**Comment by digitalbuddha** [comment]
Example of api with lambdas:
```java
        Store<RedditData, Integer> store = StoreBuilder
                .types(Integer.class, String.class, RedditData.class)
                .fetcher(barCode -> null)
                .parser(s -> null)
                .persister(barCode -> null, (barCode, s) -> null)
                .open();
```

**Comment by PaulWoitaschek** [comment]
Why is it necessary to specify the 3 class types?

**Comment by digitalbuddha** [comment]
It's not necessary. You'll have ability to specific just key and 1 type if
no parser.

**Comment by digitalbuddha** [comment]
Realized that the double generic will be a breaking api change.   I'm going to discuss tomorrow internally to see best way to move forward. Open to ideas of how to roll this out. Thinking of doing version 1.1 with a breaking change where an additional generic will need to be added everywhere.

**Comment by PaulWoitaschek** [comment]
As this library is still in its early days I'd ship new features and breaking changes quite fast.

Also I'd add a disclaimer that the general API is still a subject to change so the library can evolve fast.

**Comment by digitalbuddha** [comment]
Disclaimer added to Readme, I'll be merging #86 today and doing a snapshot build of 1.08-Snapshot.  Once we get a few other tickets closed, particularly adding Stale records for file system & a disk clear interface we will release 1.10 with all the changes.  Feel free to use 1.08-SNAPSHOT at your own risk.

**Comment by digitalbuddha** [comment]
1.08-SNAPSHOT is out @PaulWoitaschek we won't be doing integration testing until some time next week. Kindly let me know if anything seems the matter.

**Comment by PaulWoitaschek** [comment]
@digitalbuddha Where is the snapshot?
