### ISSUE TITLE
QUESTION: refreshable resource subscribers to stay subscribed after error

### ISSUE THREAD

**Issue by Rosomack** [NYTimes/Store#230]
Hi again :)

We're trying out Store now and ran into an issue. It's not possible to make refreshable subscribers stay subscribed after it emits an error.

Use case: 4 views subscribe to the same data, an error is received and displayed on all of them. When we press retry on one of the views (invoking `store.clear()`), all 4 views should receive updated data when it's successfully retrieved.

We tried using `onErrorReturn()` and wrapping the error along with the potential response, but it doesn't work. Looking at the `RealInternalStore.response` method I think it's because control is ceded to an error observable, so that's what we're going to stay subscribed to and retry instead of the original.

Any ideas?

**Comment by digitalbuddha** [comment]
We're going to give this issue some thought.  Thank you for reporting

**Comment by digitalbuddha** [comment]
I think you did hit on a weird behavior with us creating a new Error Observable.  We can change https://github.com/NYTimes/Store/blob/develop/store/src/main/java/com/nytimes/android/external/store/base/impl/RealInternalStore.java#L204 to instead propogate the throwable  through the original stream rather than creating a new errorObservable not sure if that would solve your problem though.

After we make the above change _I think_ you'll be able to use  `onErrorReturn` to keep that stream from finishing.  Open to other suggestions/pointers of how to make this work :-)

**Comment by Rosomack** [comment]
Amazing, that should work I think, but I'm not sure it would solve it
either. I experimented a bit with my own fork where I removed the
`onErrorResume` call and it didn't help... But maybe I messed something
else up.

Thanks a lot for your hard work!

śr., 21 cze 2017 o 21:55 użytkownik Mike Nakhimovich <
notifications@github.com> napisał:

**Comment by digitalbuddha** [comment]
I'll have one of our engineers play with it in am. Thank you for using our lib, the getRefreshing was a late addition and has some unexpected behavior that we'll find a solution for 😀

**Comment by digitalbuddha** [comment]
Working on tests but we seem to have a solution that will allow you to call `retry` & `retryWhen` on a `getRefreshing` observable.

**Comment by PaulWoitaschek** [comment]
This is a breaking change that caused many crashes in my app. :(

Before, onError was called an `IOException` or `HttpException`. Now it's wrapped in an RuntimeException, but I didn't catch that.

**Comment by digitalbuddha** [comment]
Ouch sorry for that. 🙁 totally missed the exception signature change. That's for bringing up not sure of we can or should do anything now.

**Comment by PaulWoitaschek** [comment]
It makes error handling now quite difficult as it's no longer the same error as the source observable.

For now I created an `Observable` that maps the exceptions:

```kotlin
class ObservableMapError<T : Any>(private val source: Observable<T>, private val errorMapper: (Throwable) -> Throwable) : Observable<T>() {

  override fun subscribeActual(observer: Observer<in T>) {
    source.subscribe(MapErrorObserver(observer, errorMapper))
  }

  class MapErrorObserver<T : Any>(val actual: Observer<in T>, val errorMapper: (Throwable) -> Throwable) : Observer<T>, Disposable {

    private var source: Disposable? = null

    override fun onSubscribe(s: Disposable) {
      if (DisposableHelper.validate(source, s)) {
        this.source = s
        actual.onSubscribe(this)
      }
    }

    override fun dispose() {
      source!!.dispose()
    }

    override fun isDisposed(): Boolean = source!!.isDisposed

    override fun onNext(t: T) {
      actual.onNext(t)
    }

    override fun onError(t: Throwable) {
      val mapped = errorMapper(t)
      actual.onError(mapped)
    }

    override fun onComplete() {
      actual.onComplete()
    }
  }
}
```

and is applied after `get` and returns the cause of the throwable if there is one - or the throwable itself if there is none.

**Comment by digitalbuddha** [comment]
Mind opening an issue?
