### ISSUE TITLE
QUESTION : LiveData compatibility

### ISSUE THREAD

**Issue by stardeux** [NYTimes/Store#231]
Hi,

Do you have any solution to use Store with the brand new LiveData Android object rather then Observable ? 
https://developer.android.com/topic/libraries/architecture/livedata.html

Otherwise are you planning to offer this possibility ?

Thanks !

**Comment by digitalbuddha** [comment]
I'm still fairly green in live data but my understanding is that you can transform an rx observable into a live data stream.

**Comment by digitalbuddha** [comment]
closing due to no action to take

**Comment by juicycleff** [comment]
Hello in interested in this. So i think it should be open

**Comment by juicycleff** [comment]
Live data demo should be implemented as its looks like the defacto for now

**Comment by digitalbuddha** [comment]
I don't think live data works well for store. Live data only deals with positive results which means you cannot pass an error through. In general nothing is stopping you from converting the observable coming out of store into a Flowable and then into a live data.

**Comment by juicycleff** [comment]
Was thinking the same too. I think I will take that approach. @digitalbuddha thanks

**Comment by ubuntudroid** [comment]
@digitalbuddha I know this is closed, but I stumbled upon this feature request while investigating on store for our apps. Regarding

> Live data only deals with positive results which means you cannot pass an error through.

You certainly can pass errors through with LiveData, just not by means of a dedicated callback like in RX, but using a wrapper result object, e.g.

```kotlin
data class Result<out T>(val data: T, val error: Error)
```

Or am I just missing your point? :)

**Comment by digitalbuddha** [comment]
Yup that's the pattern most use with live data. You're free to take store's observable/single result and transform it into livedata. I like rxjava because it gives you more control. For instance retry is easier with rx, same with zipping multiple sources. I find rxjava to be the proper abstraction for data operations.
