### ISSUE TITLE
How to update object in cache

### ISSUE THREAD

**Issue by NaikSoftware** [NYTimes/Store#235]
``` java
RestClient restClient = RestClient.getInstance();
mPollStore = StoreBuilder.<Long, Poll>key()
        .fetcher(pollId -> restClient.getPollRepository().getPoll(pollId))
        .open();
```
And when I receive event that some poll changed  and I have this poll, I want to insert updated object in Store, without retrieving from server. It is possible?

**Comment by digitalbuddha** [comment]
Currently there is no way to update something in store memory yourself. We believe unidirectional data flow leads to less errors and this would break that concept. You could always call store.frwsh again and return the new value from your fetcher
