### ISSUE TITLE
Clearing cache / disk without refresh

### ISSUE THREAD

**Issue by ychescale9** [NYTimes/Store#240]
Currently calling `store.clear()` or `store.clear(key)` calls `notifyRefresh(key);` at the end which triggers network calls.

Is there a way to clear the cache and disk without triggering refresh?

My use case is I want to clear all data in cache and disk after each of my espresso tests (by clearing the injected store instances in my test classes). 

Any direction would be appreciated. Thanks!

**Comment by digitalbuddha** [comment]
AFAIK the only time the refresh of network is triggered is when you are subscribed to `getRefreshing` otherwise there are no subscribers that get notified to repeat the fetch.

**Comment by ychescale9** [comment]
Thanks Mike.
