### ISSUE TITLE
Deprecate Store in favor of Store3

### ISSUE THREAD

**Issue by digitalbuddha** [NYTimes/Store#249]
We have been incubating the rx2 branch for a few months and have not seen any bug reports come in. As our internal codebase has switched to rx2 we are flipping https://github.com/NYTimes/Store/tree/feature/rx2 to instead be the master branch at some point next week.  This means that Store3 will be the only artifacts we support going forward.  We will also be making 1 final release of Store(1) as there have been a few bug fixes since last release.  

If there are any breaking change requests such as renaming of packages/classes/methods kindly suggest them here.

**Comment by PaulWoitaschek** [comment]
Quite some time has passed now and the latest release is still based on RxJava 1. Any news on an upcoming release?

**Comment by digitalbuddha** [comment]
Rx2 is only branch /artifacts currently supported. Not sure if any chances went in recently to warrant a release. I'll double check and cut a new release.

**Comment by ramonaharrison** [comment]
The latest artifact is based on RxJava2: https://mvnrepository.com/artifact/com.nytimes.android/store3/

There haven't been significant changes merged since this went out, mainly just a few small fixes to the sample app and docs. We'll cut a `3.0.0` release this week.
