### ISSUE TITLE
Saving via Store

### ISSUE THREAD

**Issue by sboishtyan** [NYTimes/Store#26]
Hello, now i can get, fetch or stream data. How need saving or updating my data if i using your Store for retrieve it?

**Comment by digitalbuddha** [comment]
Personally I suggest using immutable data models and never mutating them. If you need to get new values into the Store use store.fresh(barcode) which will overwrite the old data with a new entry. Could you give more specific example of what you want to do?

**Comment by sboishtyan** [comment]
What is a method `store.fresh(barcode)`? I don't find it an Store interface API.
I have payment items list with some actions on my payment, and i can pass through to payment details and change it, then i go back and want to see updated payment in list. And with my own repository implementation i have method repositoty.update(payment), and i don't need to update all list.

**Comment by digitalbuddha** [comment]
apologies I meant fetch https://github.com/NYTimes/Store/blob/develop/store/src/main/java/com/nytimes/android/external/store/base/Store.java#L29

Apologies but your use case is not how  library is intended to be used.  The only thing that can update your data is a new request.  This is to keep unidirectional data flow.
