### ISSUE TITLE
paginate data

### ISSUE THREAD

**Issue by DJafari** [NYTimes/Store#27]
thanks for your great library

can you update example to paginate data ?

**Comment by digitalbuddha** [comment]
Not sure exactly what you mean? If your request needs a page parameter you can send that through in a barcode. Mind giving me more detail? Rxjava in general can be used to combine multiple store calls into a single stream if that is what you want.

**Comment by DJafari** [comment]
for exampe a listview with endless adapter,
each page of datas must get from remote and save in memory and cache and add to adapter
with multiple barcode i can achieve to this ?

thanks
