### ISSUE TITLE
Suggestions for controlling disk cache size?

### ISSUE THREAD

**Issue by saket** [NYTimes/Store#270]
Hey folks, is it possible to set a max size on the cache rather than setting a time based expiry policy?

**Comment by digitalbuddha** [comment]
On the memory cache yes, on disk not currently. We made the store primarily a series of interfaces that you need to implement. The current FileSystemPersisters implementations are just our use case to serve as examples,  but if you write your own persister implementation you can implement RecordProvider in any manner you see fit. When  a store checks for staleness it will delegate back to your implementation. Our Filesystem does not currently expose size information and I'm not sure if there is a nice generic way to do this without adding some logic to associate multiple file system cache records as being part of same store.

**Comment by pavlospt** [comment]
FileSystem could expose size information by checking all KeyResolvers associated possibly? Then have FilerSystem apply a Staleness policy and either clear according to lastmodified or just decline to write new cache records?

**Comment by digitalbuddha** [comment]
Keys aren't guaranteed to have any association. If in your app they do then the implementation of this would be trivial.

**Comment by pavlospt** [comment]
Any association with what?

**Comment by saket** [comment]
The problem with staleness policy is that it's only checked when a new request is received with the same key. In my use case, I don't want my disk cache to ever expire but I also want to ensure it does not grow to a huge size. What other options do we have?

**Comment by digitalbuddha** [comment]
Sounds like you should have your persister be a disk lru cache. Also easy to hook into store ☺️

**Comment by saket** [comment]
Small update: I created a file-system implementation with DiskLruCache: https://gist.github.com/Saketme/bcf94b25b28d0971949d3ac723aebf91

This was easy. Ensuring that `PathResolver`s create DiskLruCache compatible paths was a bit difficult because it only accepts `[a-z0-9_-]{1,64}`.
