### ISSUE TITLE
RealStore with Fetcher<Raw,Key> , Persister<Parsed,Key> and Parser<Raw,Parsed> ?

### ISSUE THREAD

**Issue by magillus** [NYTimes/Store#275]
I have use case where the RealStore constructor would be needed:
Current code:
```
    public RealStore(Fetcher<Parsed, Key> fetcher,
                     Persister<Parsed, Key> persister) {
   ...
    public <Raw> RealStore(Fetcher<Raw, Key> fetcher,
                           Persister<Raw, Key> persister,
                           final Parser<Raw, Parsed> parser) {
```
I would like to add:

  ```
  public <Raw> RealStore(Fetcher<Raw, Key> fetcher,
                           Persister<Parsed, Key> parsedPersister,
                           final Parser<Raw, Parsed> parser,
                           final Persister<Raw, Key> responsePersister //optional
                 ) {
```
What I would expect from such store is to fetch from Fetcher `Raw` and parse with `parser` then store with `parsedPersister` also fallback (optional) `responsePersister`  - like file

the `parsedPersister` could be db storage that the requested data would parse and update.

My current solution is first constructor and Fetcher does parsing

**Comment by digitalbuddha** [comment]
That one is tricky since it will break/fork the internal logic of how stores work, currently the data flow is to parse any source coming from network or disk. The reason for this is to allow streaming from network clients to disk.  To add this feature we would need to someone restrict the streaming api.  Since a fetcher's return is an `Observable` I think your best bet is to do what you are doing and use 
``` 
public RealStore(Fetcher<Parsed, Key> fetcher,
                     Persister<Parsed, Key> persister)
 ```

but have your fetcher implementation look something like 
`key->fooApi.makeRequest().map(it->fooParser.parse(it)`

**Comment by magillus** [comment]
Thank you for response, I see the reason for it.
That is what I do right now, my Fetcher wraps network layer fetcher and parser.

```
abstract class BaseFetcher<Parsed, Key>(private val rawFetcher: Fetcher<BufferedSource, Key>,
                                        private val parser: Parser<BufferedSource, Parsed>)
    : Fetcher<Parsed, Key> {
    override fun fetch(key: Key): Single<Parsed> {
        return rawFetcher.fetch(key).subscribeOn(Schedulers.io())
                .map(parser)
    }
}
```

and calling `RealStore<Parsed, Key>(networkFetcher:BaseFetcher<Parsed, Key>, dbPersister: Persister<Parsed, Key>)`

**Comment by digitalbuddha** [comment]
Yup thats it!.  We'd happily accept a PR for your BaseFetcher renamed as ParsingFetcher.  I think others would  love an api thats something like 
```
RealStore<Parsed, Key>(ParsingFetcher.from(fetcher,parser):Fetcher<Parsed,Key>, dbPersister: Persister<Parsed, Key>)
```
