### ISSUE TITLE
How to retry on encountering  401 error, with refreshing token 

### ISSUE THREAD

**Issue by rinav** [NYTimes/Store#276]
Thank you for the amazing library.

We have started to implement Store and are stuck with the following scenario.
How to handle token expiration returned by HTTP status code 401, when using a fetcher to fetch new 'Topics'.
Basically I would like to catch 401 status code and send a new network call to refresh token, get new one and save it locally and finally retry the same call.

I am able to detect 401 via a simple compose and get the error in doOnError, but unable to retry the fetcher, with new login token 

    private fun provideNonPersistedStore(): Store<TocicResponse, String> {

        return StoreBuilder.key<String, TocicResponse>()
                .fetcher { token ->
                    newsService.getUserTopics("cricket")
                            .compose(SingleStatusCodeVerifierTransformer<TocicResponse>())

                            .doOnError {
                                e -> Timber.e(e, "caught in Topic store")
                                if (e is Status401Exception) {
                                    Timber.e("token expired")

                                    Timber.d("now trying with %s token", token)
                                    newsService.checkTokenValidity(token)

                                            .subscribeOn(Schedulers.io())
                                            .observeOn(AndroidSchedulers.mainThread())
                                            .subscribe(object : Observer<Response<VerifyTokenResponse>> {

                                                override fun onComplete() {
                                                    Timber.d("now trying with %s token onComplete")
                                                }

                                                override fun onNext(t: Response<VerifyTokenResponse>) {
                                                    Timber.d("now trying with %s token onNext")
                                                    val userTopics =
                                                    
                                                    newsService.getTopics(t.body()?.tokenMessage?.loginToken)
                                                    
                                                    //Observable.just(userTopics)
                                                    return Single.just(userTopics)

                                                }

                                                override fun onError(e: Throwable) {
                                                    Timber.d("now trying with %s token onError")
                                                }

                                                override fun onSubscribe(d: Disposable) {
                                                    Timber.d("now trying with %s token onSubscribe")
                                                    //d.dispose()
                                                }
                                            })
                                }
                                else {

                                    Timber.e(e, "no this is not 401 error :(")
                                    return@doOnError
                                }
                            }
                }
                .memoryPolicy (
                        MemoryPolicy
                                .builder()
                                .setExpireAfterWrite(Constants.IN_MEMORY_CACHE_EXPIRES)
                                .setExpireAfterTimeUnit(TimeUnit.MINUTES)
                                .build()
                )
                .open()
    }

Below is the Simple compose class

    public class SingleStatusCodeVerifierTransformer<T> implements SingleTransformer<Response<T>, T> {

    @Override
    public SingleSource<T> apply(Single<Response<T>> upstream) {

        return upstream.flatMap(new Function<Response<T>, SingleSource<T>>() {
            @Override
            public SingleSource<T> apply(Response<T> httpResponse) throws Exception {

                switch (httpResponse.code()) {
                    //TODO check httpResponse.body() to be non null
                    case 200: return Single.just(httpResponse.body());
                    case 400: return Single.error(new Status400Exception(ProjectConstants.EXCEPTION_CODE_400));
                    case 401: return Single.error(new Status401Exception(ProjectConstants.EXCEPTION_CODE_401));
                    case 403: return Single.error(new Status403Exception(ProjectConstants.EXCEPTION_CODE_403));
                    case 404: return Single.error(new Status404Exception(ProjectConstants.EXCEPTION_CODE_404));
                    default:  return Single.error(new Exception("unknown error: " + httpResponse.code()));
                }
            }
        });

**Comment by Aneeshassa** [comment]
I am facing a similar issue, can you guide me how to deal with it.

**Comment by stoyicker** [comment]
This isn't something to take an action on at the Store-level, but at the OkHttp one: https://square.github.io/okhttp/3.x/okhttp/okhttp3/Authenticator.html

Pass an Authenticator to your Retrofit OkHttp client that refreshes your token.

**Comment by digitalbuddha** [comment]
Does the link above solve your problem? Ideally you are using okhttp which can manage authentication for you. I don't believe that should be handle by your repository/Store but rather your network client. If not using okhttp is there another way you can write an interceptor to validate responses and reauthorize?
