### ISSUE TITLE
Question about get() method

### ISSUE THREAD

**Issue by aitorvs** [NYTimes/Store#281]
I was taking a look at this fantastic library and I got a bit confused with the behavior of `get` method.
My example is quite simple. Single activity that fetches pics from Flickr.

In the `MainActivity` I have the following code (in `onResume()`):

```java
        disposable.add(searchPhotos
            .flatMap(search -> photoStore.get(search).toObservable()
                .onErrorReturn(Resource::error)
                .observeOn(AndroidSchedulers.mainThread())
                .startWith(Resource.loading())
            )
            .observeOn(AndroidSchedulers.mainThread())
            .subscribe(r -> {
                ptr.setRefreshing(r.isLoading());
                if (r.isSuccess()) {
                    photoAdapter.accept(r.data);
                }
            }, OnErrorNotImplementedException::new)
        );
```

The Store is created as:

```java
    Store<Resource<FlickrData>, PhotoRequest> providePhotoStore(PhotoService photoService) {
        return StoreBuilder.<PhotoRequest, Resource<FlickrData>>key()
            .fetcher(fetchFlickrPhotos(photoService))
            .memoryPolicy(MemoryPolicy
                .builder()
                .setExpireAfterWrite(TimeUnit.MINUTES.toSeconds(10))
                .setExpireAfterTimeUnit(TimeUnit.SECONDS)
                .build())
            .open();
```

And the key is an object `PhotoRequest` that is basically as the following:

```java
@AutoValue
public abstract class PhotoRequest implements Parcelable {
    public abstract String search();
    public abstract Integer page();
}
```
The app fetches 20 items/page and when the user scrolls to the bottom of the app, it fetches the next page.

I have noticed the following in the following use case:
Scenario:
- Scroll to get three pages
- home the app
- get back to the app

Expected behavior:
- the last search object has `page()` == 3

Behavior:
- the store however returns **all** the items previously fetched (all 3 pages == 60 items).

Why is that? 

Thanks for this fantastic library.

**Comment by alexio** [comment]
Not sure why it would be returning all the previously fetched items for when the key has a `page() == 3`. We don't append responses to each other. Which Flickr api are you using? I'll try to duplicate it on my end.

**Comment by aitorvs** [comment]
My apologies! Just debug my sample app and it was a bug in my adapter :D

I will close the issue!
