### ISSUE TITLE
QUESTION: inter-op with Kotlin

### ISSUE THREAD

**Issue by aitorvs** [NYTimes/Store#288]
I flagged this as a question as I am not sure it is an inter-op issue with Kotlin.

I have created a very simple `Store` in Kotlin like this

```java
fun testStore(): Store<ResourceViewState, Int> = StoreBuilder.key<Int, ResourceViewState>()
    .fetcher({ Single.just(ResourceViewState.Error(RuntimeException("Asked for ${it}days"))) })
    .open()
```

*NOTE: The `ResourceViewState` is a `sealed class` but here this is not important*

I am trying to use the store with this code:

```java
disposable.add(Observable.interval(1000L, MILLISECONDS)
    .map { it.toInt() }
    .doOnNext { Timber.d("$it") }
    .flatMap {
        testStore().get(it).toObservable()
            .observeOn(AndroidSchedulers.mainThread())
            .startWith { ResourceViewState.Loading() }
    }
    .observeOn(AndroidSchedulers.mainThread())
    .doOnNext { Timber.d("onNext") }
    .subscribe({ marketPrice = it }, { OnErrorNotImplementedException(it) }))
```

To my surprise, only the first `doOnNext` is logged, and nothing else.

Do you know why this might be?

Thanks a lot!

**Comment by digitalbuddha** [comment]
I'll look at it a bit later, not sure what the issue is, definitely not kotlin as we use it with store all the time.  I think it might have smth to do with store returning a single which has a terminal operator after 1 emission

**Comment by aitorvs** [comment]
Thanks a lot! 
I pointed to Kotlin because I had used that pattern in Java and worked just fine O_o
But I can't figure what is wrong here.

**Comment by pavlospt** [comment]
@aitorvs do you have a repo with a repro of the issue so that we could debug it?

**Comment by sevar83** [comment]
Try with:

`.startWith(ResourceViewState.Loading())`. This thing bit few times.
Lost several hours to figure out the stupid brackets were the mistake.

**Comment by aitorvs** [comment]
@sevar83 Thanks a ton! didn't even see those damn brackets O_o

Thanks to all too. And sorry for raising the issue!

**Comment by sevar83** [comment]
This is a really nasty little thing. There was a discussion on Reddit
specifically about it. But couldn't find it.

**Comment by pavlospt** [comment]
@sevar83 you are totally right. We had that in the past as well. There should be a Lint check or something for it !!
