### ISSUE TITLE
NoopPersister crashes if expire-after-access memory policy is set

### ISSUE THREAD

**Issue by saket** [NYTimes/Store#312]
Hello, it appears that `Store` doesn't consider expire-after-access policy when a persister isn't present. The constructor of [NoopPersister(MemoryPolicy)](https://github.com/NYTimes/Store/blob/4109df3a336d6b73d29afdd351b683f388328ae1/store/src/main/java/com/nytimes/android/external/store/util/NoopPersister.java#L26) only includes expire-after-write rule when building its `networkResponses` field, resulting in an exception.

**Comment by digitalbuddha** [comment]
Yup that's a bug 🙂 want to pr a fix?

**Comment by saket** [comment]
Yep, looks like a small change. I will try doing it this weekend.

**Comment by saket** [comment]
Sorry it took this long for me to send a PR. I was traveling. I've opened a PR here: #315
