### ISSUE TITLE
Store for Java?

### ISSUE THREAD

**Issue by stoyicker** [NYTimes/Store#317]
I was thinking today about Store and it being an Android library. That's cool and all, but upon a superficial search on GitHub there doesn't seem to be a reason to it - its important dependencies are RxJava, Retrofit, Moshi, Gson and Jackson, none of which are Android-specific, and I didn't find any android.* imports. Only thing that would seem to be required as far as I can see is a bit of a refactoring regarding things like removing android manifests, and I'd be happy to do it. What do you think of this? Is it something you'd be open to?

**Comment by ramonaharrison** [comment]
I don't see any reason not to do this -- it would be great to make Store available for a wider set of uses.

If this is something you're interested in doing, we'd welcome a PR.

**Comment by stoyicker** [comment]
Thanks, I'll see what I can get together this weekend.
