### ISSUE TITLE
Encryption?

### ISSUE THREAD

**Issue by The0ldM0nk** [NYTimes/Store#318]
Does it support Encryption as a feature?

**Comment by ramonaharrison** [comment]
Hi, there isn't support for encryption built in but you can write your own Fetcher or Persister to handle encryption as you wish using something like https://github.com/tozny/java-aes-crypto.

**Comment by The0ldM0nk** [comment]
@ramonaharrison hey, thanks for the reply. I'll be closing this ticket for now 👍
