### ISSUE TITLE
Maximum size of memory cache is by default 1

### ISSUE THREAD

**Issue by saket** [NYTimes/Store#321]
`MemoryPolicyBuilder` defaults to `1` as the max-size. Is this a mistake? Or does this get overridden somewhere else?

**Comment by digitalbuddha** [comment]
You can pass in a new Max-Size in the builder https://github.com/NYTimes/Store/blob/feature/rx2/store/src/test/java/com/nytimes/android/external/store3/base/impl/MemoryPolicyBuilderTest.java#L55

**Comment by saket** [comment]
True, but when a `MemoryPolicy` is built with an expiry policy, the max-size defaults to 1 unless specified by the user:

https://github.com/NYTimes/Store/blob/d182147d65df3d9a8e1e0718b84c89ff72838c69/store/src/main/java/com/nytimes/android/external/store3/base/impl/MemoryPolicy.java#L91

**Comment by digitalbuddha** [comment]
That seems like a bug. Want to pr a fix?

**Comment by saket** [comment]
Sure. What value should we default to?

**Comment by digitalbuddha** [comment]
@pavlospt offered to get the fix in. If no progress in few days I'll ping you 🙂

Great find btw! I guess I just always set all the policy flags explicitly in personal use.

**Comment by pavlospt** [comment]
Hey @digitalbuddha & @Saketme, I opened a PR https://github.com/NYTimes/Store/pull/328. LMK if this is ok or you need any other modifications!

**Comment by saket** [comment]
Oh nice. Thanks @pavlospt!

**Comment by wdziemia** [comment]
#328 Merged, closing issue
