### ISSUE TITLE
[Q] Differents between SourcePersisiter and FileSystemPersisiter?

### ISSUE THREAD

**Issue by Guang1234567** [NYTimes/Store#325]
Hello dev:

what is the differents between `SourcePersister` and `FileSystemPersister`?

**Comment by digitalbuddha** [comment]
They are just about the same. One works on Barcodes only while the other can work on a key of any type. We keep both for backward compatibility

**Comment by Guang1234567** [comment]
@digitalbuddha 

Thanks your expain explain.
