### ISSUE TITLE
Question about unidirectional flow

### ISSUE THREAD

**Issue by qazt482** [NYTimes/Store#327]
> exposing a Reactive API built with RxJava that adheres to a unidirectional data flow.

My understanding of unidirectional data flow is where there are two independent processes. One is writing data to some store (either scheduled or initiated by the ui) and has no return data and the other is listening for changes to the store.

This way, if the data changes, the ui automatically changes. The examples of Store here, require the UI to request and then display data. If data changes behind the scenes, the ui will not know since it does not poll.

Is this correct understanding?

**Comment by digitalbuddha** [comment]
We do have the functionality you are describing. You can subscribe to store.stream(key).  Then anytime you call store.get(key) and get to a new network request, the store will emit the value to everyone that is subscribed to store.stream.  You can also call store.fresh to fire a new push to everyone subscribing to store.stream.  

Generally what is meant I meant by unidirectional data flow is that network updates disk which updates memory which you read from. You never directly write to memory or read from disk or do anything else. Only new emissions from a fetcher can update anything in a  store and only subscribing to it can get the data. Hope that helps

**Comment by qazt482** [comment]
Thanks! I'll investigate further.
