### ISSUE TITLE
How to know if the result obtained from get() method is from cache, or fresh from network?

### ISSUE THREAD

**Issue by ferrytan** [NYTimes/Store#331]
Hello, i've been using the offline-first example using:
`myStore.get(barcode).concatWith(myStore.fetch(barcode)).distinct();`

I have one question about this feature.
I did exactly the same scenario with this, but i have a problem that each GET operation is also being used as analytic data.
My problem is when calling get() then fetch() for the first time (no cache at all) 
as said from this issue: #34 
it will hit the network, then hit the same network again causing 2 api calls sequentially. 
That causes a problem in my server side which counts as double analytic data on the backend.
is there any way to skip calling fetch() when get() hits network?
or any method to know the result was obtained from cache/network.

thank you

**Comment by pavlospt** [comment]
You can do something like the following 
`store
        .getWithResult(itemId)
        .toObservable()
        .switchMap {
          return@switchMap if (it.isFromCache) {
            Observable
                .just(it)
                .concatWith(
                   store.fetchWithResult(itemId)
                )
          } else {
            Observable.just(it)
          }
        }`

@charbgr can let you know more about the differences on *WithResult mehods and Result itself!

**Comment by ferrytan** [comment]
Wow! i just knew the *WithResult method and it's exactly what i needed!
i'm still using java, so my solution is to do it like this:
`store.getWithResult(barcode).toFlowable().switchMap(fResult -> { if (fResult.isFromCache()) return Single.just(fResult.value()).concatWith(store.fetch(barcode).onErrorResumeNext(throwable -> store.get(barcode))).distinct(); else return Flowable.just(fResult.value()); })`
i'm closing this issue, thank you for the solution @pavlospt !
