### ISSUE TITLE
Fetch All Feature Request

### ISSUE THREAD

**Issue by sdoward** [NYTimes/Store#333]
I have a use case where I would like to get the current item stored in cache that comes from any key. It would be something similar to `stream` but return the current value rather than the future outputs. 

This could be represented as a `Single` which would wait for the next item or `Maybe` which would return if a value is present and complete if not. 

Similarly it would be useful if `stream` or some similar method could return the current value as well as future values.

**Comment by Rickrod82** [comment]
Value account demand

**Comment by sdoward** [comment]
@Rickrod82 what do you mean?

**Comment by digitalbuddha** [comment]
I'd recommend interfacing directly with your Persister implementation rather than going through store. I'm hesitant to add this feature as we try to keep our api surface as small as possible. Since we delegate to your persister you can have whatever additional api or functionality you need there

**Comment by sdoward** [comment]
I am not using a Persister. This is a use case for an in-memory cache

**Comment by digitalbuddha** [comment]
That makes sense. I'll add it this weekend
