### ISSUE TITLE
Observe changes in disk without invalidating cache

### ISSUE THREAD

**Issue by saket** [NYTimes/Store#337]
One of my use-cases for Store is to provide a in-memory cache for a SQLite backed disk storage. This disk storage is updated from multiple places, but since Store only reads a single value from the persister, the updated values never get delivered to subscribers. 

Is there a solution to this? The `clearMemory()` doesn't work, so I cannot force invalidate the in-memory cache. Is it even worth using Store here?

**Comment by digitalbuddha** [comment]
#338 will fix your issue, it won't be Room specific but will be a reimplementation of the Store base class & Persister to allow observables rather than singles from disk

**Comment by saket** [comment]
Niceee!
