### ISSUE TITLE
Example about cache first then network

### ISSUE THREAD

**Issue by jaychang0917** [NYTimes/Store#34]
Thanks for creating a great library.

I have a use case that show cache data first and then get data from network in order to show latest data. May I ask how to implement this requirement using Store?

Thanks.

**Comment by digitalbuddha** [comment]
Thanks for kind words!

Here's what you should do followed by explanation:
`Observable.concat(store.get(),store.fetch()).subscribe()`

The first `get` call will try to go to the cache and return the value, if the cache value does not exist, it will then hit the network and return fresh data.  Then when the `fetch()` call is made it will also attempt to hit the network. If however get already hit the network for the same exact request (within the last minute) the in flight debouncer will return the same result.  

So you basically haver 3 scenarios:
if data is cached:
observable emits 2 values (cached and network)
if data is not cached:
observable emits 2 values (network and same network response)

One optimization you can make is 
`Observable.concat(store.get(),store.fetch()).distinct().subscribe()`
with `distinct` if the data was not cached your `subscriber` will only get 1 response.

Hope that clears it up!
