### ISSUE TITLE
Question: Shouldn't Persister.write return single which will write to cache only after subscribe?

### ISSUE THREAD

**Issue by kalpeshp0310** [NYTimes/Store#344]
In code example of [Disk Caching](https://github.com/NYTimes/Store/blob/feature/rx2/README.md#disk-caching) section in Read me, should't write happen when `Single<Boolean>` returned from `Persister::write()` function is subscribed?

**Given Example:**
```
@Override
public Single<Boolean> write(BarCode barCode, BufferedSource source) {
  userImplementedCache.save(key, source);
  return Single.just(true);
}
```

Shouldn't above be changed like this?

```
@Override
public Single<Boolean> write(BarCode barCode, BufferedSource source) {
  return Single.fromCallable(() -> {
    userImplementedCache.save(key, source)
    return true
  });
}
```

**Comment by digitalbuddha** [comment]
Since the only time the persister gets written to is from a flatmap off of the fetcher's observable I don't believe it will matter. The write function will run on whatever thread the fetcher's observable was subscribed on.

**Comment by kalpeshp0310** [comment]
Ahh, got it. Thanks for the update.
