### ISSUE TITLE
RxJava 2 support?

### ISSUE THREAD

**Issue by scottmeschke** [NYTimes/Store#36]
This is a pretty sweet little library, it's very similar to something I've been working on myself.
But RxJava 1 would makes me sad when inter-oping with the rest of my application code.

Any plans to update to RxJava 2?

The signifigant performance gains, Reactive Streams spec compliance, and Flowable vs Observable distinction alone makes it worth updating imo.

I would be willing to contribute or start a PR if there is interest.

**Comment by digitalbuddha** [comment]
I was hoping to wait until some larger libraries like Retrofit make the plunge. Is it just  the public api you want to change or all rxjava1 to 2? I'm worried that current adoption of rx2 is low.  Will keep open

**Comment by riclage** [comment]
Retrofit already supports RxJava 2 via an [adapter](https://github.com/JakeWharton/retrofit2-rxjava2-adapter).

My vote goes for changing everything to Rx 2 as keeping both dependencies increase the method count quite significantly. It could also be a solution that abstracts away the Rx dependency from this library altogether (e.g., using adapters).

**Comment by digitalbuddha** [comment]
@scottmeschke I'd be open to figuring out a way to abstract RxJava stuff into adapters so that both Rx1 & Rx2 will work, I don't believe this would be trivial but at the same time possible.  Feel free to play with it (along with anyone else that wants rx2 support before we convert internally)

**Comment by PaulWoitaschek** [comment]
I'd just make the transition to the latest version of RxJava and tell people with Lacey m legacy to use the interop library. 

Rx2 is the future.

**Comment by pwittchen** [comment]
> tell people with old versions to use the interop library
Is there any interop solution, which allows converting RxJava2 to RxJava1 code? As far as I know [RxJava2Interop](https://github.com/akarnokd/RxJava2Interop) does this thing the other way around.

**Comment by PaulWoitaschek** [comment]
Both ways @pwittchen

**Comment by digitalbuddha** [comment]
We are making the jump to rx2 internally. Will give this a whirl soon. If anyone wants to convert feel free to start ☺️

**Comment by PaulWoitaschek** [comment]
Does this go together with #22

**Comment by digitalbuddha** [comment]
Yeah I guess its going to have to since some operators return single by default.. Good question!

**Comment by PaulWoitaschek** [comment]
@digitalbuddha What about lambdas? With retrolamba it just compiles to bytecode like everything else and that would make the work way easier!

**Comment by digitalbuddha** [comment]
My only concern is the additional methods that are added. Last I checked retrolambda turned each `call` into 3 methods.

**Comment by pavlospt** [comment]
There is no need to add Retrolambda as an extra dependency. No obvious advantage of using it.

**Comment by digitalbuddha** [comment]
So I think what @PaulWoitaschek  is getting at is that the refactoring is much easier if we are dealing with Lambda's rather than having to refactor each anonymous class to be a different class.

**Comment by maksim-m** [comment]
Are you planning to drop support for RxJava v1 completely in one of the next releases?

Maybe you could create a new branch for only RxJava v2 version so others can send PRs against it?

**Comment by digitalbuddha** [comment]
My thought was to make 1x branch Deprecated in few releases. Then do only new development on 2.x.  If something is critical I guess it can be done in the other branch too. Like mentioned above there is an interop libraries plus it seems square is starting to convert their libs.  Thoughts?

**Comment by maksim-m** [comment]
Sounds good. So, you want to make this changes directly in develop branch, and create a new branch for RxJava v1 version, right?

**Comment by digitalbuddha** [comment]
Yup that sounds reasonable.

**Comment by digitalbuddha** [comment]
there is an experimental branch in progress.  We have another issue for tracking #167
