### ISSUE TITLE
fetchWithResult returns NETWORK even on network errors

### ISSUE THREAD

**Issue by fabioCollini** [NYTimes/Store#381]
The `fetchWithResult` method always returns a `Result` created using `createFromNetwork`:

```
public Single<Result<Parsed>> fetchWithResult(@Nonnull Key key) {
    return fetch(key).map(Result::createFromNetwork);
}
```

The problem is that if there is an error the `fetch` method loads the data from the cache but the result is created using `createFromNetwork`.
I can work to fix it but unfortunately it doesn’t seem easy to fix, the only solution I can find is to refactor the `fetch` and  `fetchWithResult` in the `RealInternalStore` class. The `fetch` method should call `fetchWithResult` and execute a map to return just the data. What do you think?

**Comment by digitalbuddha** [comment]
close?

**Comment by fabioCollini** [comment]
Yes!
