### ISSUE TITLE
This library seems to be deprecated. Other alternatives?

### ISSUE THREAD

**Issue by galcyurio** [NYTimes/Store#391]
There are no commit after March 2019.

Unfortunately, we have no alternatives. There are many cache libraries, but they are not already managed. [FriendlyRepo](https://github.com/friendlyrobotnyc/FriendlyRepo), the fork of this library, is also no longer managed.

I've searched the libraries used on JVM, not just Android. Among them, [caffeine](https://github.com/ben-manes/caffeine) looks good.
But Android is not supported. See [here](https://github.com/ben-manes/caffeine/issues/293).

Please let me know if you find a good alternative.

**Comment by digitalbuddha** [comment]
Will be announcing a new main repo in 3 days stay tuned
