### ISSUE TITLE
Add precondition checks

### ISSUE THREAD

**Issue by digitalbuddha** [NYTimes/Store#41]
This ticket is a bit open ended. Add precondition checks where necessary.

**Comment by scottmeschke** [comment]
did you want to do inline, or with some kind of Preconditions class with some methods to resuse everywhere? I see the one in the cache from Guava, but if you wanted to use that everywhere you'd want to move it to the base artifiact I'm guessing.

**Comment by digitalbuddha** [comment]
Guava one preferably. I'm pretty sure everything depends on Cache since
it's a dependency of Store. Internally we use Guava but to keep method
count down we don't have access here. I'm OK copying in other guava
preconditions if they are needed.

**Comment by brianPlummer** [comment]
https://github.com/NYTimes/Store/pull/56
