### ISSUE TITLE
Question: Parsing From API which returns List<T>

### ISSUE THREAD

**Issue by Jogan** [NYTimes/Store#43]
Thanks for open sourcing this solution!

Had question about how you typically handle an API which returns a List<T> and parsing it. I'm currently doing:

```java
final Store<List<FooItem>> store = ParsingStoreBuilder.<BufferedSource, List<FooItem>>builder()
          .fetcher(barCode -> api
              .getFooItems()
              .map(ResponseBody::source))
          .persister(persister)
          .parser(source -> {
            try (InputStreamReader reader = new InputStreamReader(source.inputStream())) {
              return gson.fromJson(reader, new TypeToken<List<FooItem>>() {}.getType());
            } catch (IOException e) {
              throw new RuntimeException(e);
            }
          })
          .open();
```

There is really nothing wrong with this and everything works as expected. Maybe grounds for an enhancement to the middleware down the road unless I'm missing something obvious?

**Comment by digitalbuddha** [comment]
Are you saying default gson parsing does not work? Why do you need to pass in the type token?

**Comment by digitalbuddha** [comment]
Seems like we  need another Middleware for top level jsonarray. Want to pr something in? I can take a look at it tomorrow otherwise.

**Comment by Jogan** [comment]
@digitalbuddha check out #44. I'm fairly new to contributing. Let me know how it looks.

**Comment by digitalbuddha** [comment]
I pushed up a 1.3-Snapshot to mavens snapshot repo if you want to use it now. I'm going to take another look tonight and might merge it with the regular Middleware by having 2 constructors.

**Comment by Jogan** [comment]
@digitalbuddha sounds good thanks!

**Comment by digitalbuddha** [comment]
Fixed by https://github.com/NYTimes/Store/pull/46

**Comment by digitalbuddha** [comment]
new snapshot deployed 1.0.3-SNAPSHOT should be up shortly. Thank you for your help today on getting the ball rolling.

**Comment by aysha319** [comment]
i try to use this #46 solution in my project
`storeMonth= StoreBuilder.
                    <BarCode,BufferedSource,ArrayList<Event>>parsedWithKey()
                    .fetcher(barCode -> getDataManager().getAllEventsParsed(barCode))
                    .parser(GsonParserFactory.createSourceParser(new Gson(), new TypeToken<ArrayList<Event>>(){}.getType()))
                    .persister(new RecordPersister(FileSystemFactory.create(file), 1,TimeUnit.DAYS))
                    .open();`

in fetcher i have to convert my - list in TypeToken -  to bufferedSource and viseversa in subbscrib of store right?
how can i do this in java?
i try but its return null
anyone can help me?

**Comment by aysha319** [comment]
hi @Jogan 
can i ask what exactly are you doing in this part?
`.map(ResponseBody::source)`
