### ISSUE TITLE
Versioning history deleted

### ISSUE THREAD

**Issue by PaulWoitaschek** [NYTimes/Store#51]
I saw you deleted the version history for 1.0.0 and 1.0.1. It would be great if you could keep old versions intact so its easier to follow the progress and track issues.

**Comment by digitalbuddha** [comment]
Sorry not sure what you mean? We just started a changelog https://github.com/NYTimes/Store/blob/develop/CHANGELOG.md

**Comment by PaulWoitaschek** [comment]
On the release page and as tags there is only 1.0.2. If this is really the first tag this issue can be closed.

**Comment by digitalbuddha** [comment]
Yup, we were lazy before.  Thanks for keeping us honest 💯 enjoy your day
