### ISSUE TITLE
Annotation Processor to  generate Stores for Retrofit Interfaces 

### ISSUE THREAD

**Issue by digitalbuddha** [NYTimes/Store#54]
It would be nice to write a code generator that could read Retrofit annotations and generate a store instance for it. The nice part about this setup is that you can make Barcodes specific to the params being passed in.

**Comment by eneim** [comment]
"Store" doesn't need to be strictly used with Retrofit, your proposal should be a 3-rd party plugin :D.

**Comment by digitalbuddha** [comment]
It absoutely would be a seperate module/artifact. This is merely a convenience the way the Middleware is. Thinking about it more you don't even need to read annotations, just field types/names.

**Comment by digitalbuddha** [comment]
Step 1. Generate fetcher and Barcodes. 
Step 2. Generate store for BufferedSource input only 
Step 3. Add our own annotations to drive stores with and without persister/caches

**Comment by michaldrabik** [comment]
Could you provide an example of how should it look like? For example lets take `Api` interface from the sample app. Should the generator take both methods (annotated with `    @GET("r/{subredditName}/new/.json")
`) and generate Stores for `RedditData` and `ResponseBody`. Or should we be able to annotate particular methods.

Maybe I am missing something?

**Comment by digitalbuddha** [comment]
I'm actually going to bang this out tomorrow. What I was thinking is annotate the entire class with @Stores which would generate a store for each Get request.   You'd have to pass a factory that can create a gson instance to the annotation. You'd also need to pass the factory that creates a file system. Sorry still half an idea. I'll open a pr tomorrow and we can refine from there.

**Comment by digitalbuddha** [comment]
not done but its a start: currently generating custom `Barcodes` and a Module that can be extended or used with Dagger to create `Stores` 
https://github.com/NYTimes/Store/pull/64

**Comment by digitalbuddha** [comment]
Dying on the vine but moshi adapter syntax gave me some ideas.
