### ISSUE TITLE
Allow multiple parsers. 

### ISSUE THREAD

**Issue by digitalbuddha** [NYTimes/Store#57]
Currently you can only pass in a single parser. There are times when I want to use a Middleware parse plus add additional parser. 

Ideally I should be able to do:
Builder.fetcher().parser(firstParser).parser(secondParser).build()

A solution should be found that does not require any additional generics while allowing any number of parsers to be used in serial.

**Comment by michaldrabik** [comment]
What would a real life scenario be, where you need multiple parsers?

**Comment by digitalbuddha** [comment]
Let's say when you first want to use a Middleware parser to convert from json to pojos. Then you want to rearrange the data for example flattening an api that has nested nodes

**Comment by michaldrabik** [comment]
OK, so like: JSON --> POJO1 --> POJO2 (different type than POJO1)

**Comment by digitalbuddha** [comment]
Yup! It will make it easier to share some parsers and then build on top of them without needing to subclass
