### ISSUE TITLE
Clarifying Store.stream

### ISSUE THREAD

**Issue by PaulWoitaschek** [NYTimes/Store#72]
Currently I find the implementation of `stream(barcode)` very confusing. 

If I understand correctly, it makes a call with the barcode and then returns all results of all barcodes.
But before reading the documentation I thought that it would stream everything that matches to the barcode.

My suggestion is to remove the barcode from the signature of stream. And to make stream() completely passive (like the method implicates to me).

If someone wants the behavior of what it does currently, he could just use RxJava to archieve exactly that, i.e. `Observable.conat(store.get(barcode), store.stream())`.

**Comment by digitalbuddha** [comment]
Makes sense. Want to PR?

**Comment by PaulWoitaschek** [comment]
I'll give it a try.

**Comment by digitalbuddha** [comment]
Sure. I can get it done over weekend too. Deprecated current implementation, I'll pull it out in 1.1

**Comment by PaulWoitaschek** [comment]
Like this? Couldn't resist from making a small cleanup.
