### ISSUE TITLE
Pure java library?

### ISSUE THREAD

**Issue by PaulWoitaschek** [NYTimes/Store#83]
If I see correctly there is no dependency on the Android SDK. Why isn't it a pure java library?

When I want to experiment with the store I usually just want to fire up intellij and test things on my local machine without the need of a device.

**Comment by digitalbuddha** [comment]
It's in progress as part of code gen pr. You're totally right. I was lazy and did it work. Will fix.

**Comment by PaulWoitaschek** [comment]
Nice 👍
