### ISSUE TITLE
Having problem in building this project 

### ISSUE THREAD

**Issue by ankitPagalGuy** [NYTimes/Store#9]
I am trying to build but I am facing this problem 

Error:Unknown host 'artifactory.em.nytimes.com: unknown error'. You may need to adjust the proxy settings in Gradle.
<a href="toggle.offline.mode">Enable Gradle 'offline mode' and sync project</a><br><a href="https://docs.gradle.org/current/userguide/userguide_single.html#sec:accessing_the_web_via_a_proxy">Learn about configuring HTTP proxies in Gradle</a>

In my android studio Proxy is enabled , Do I need to give proxy configuration url ? or am I missing something ?

**Comment by digitalbuddha** [comment]
Oops we still had our internal artifactory in top level maven. Want to open a pr removing artifactory.em.nytimes.com here? https://github.com/NYTimes/Store/blob/40ebbcc62f3986d055bb7bfd2648b8473ad4b846/build.gradle#L10

Alternatively give me few hours and I'll get it in when I'm at work.

**Comment by ankitPagalGuy** [comment]
I guess this also needs to be removed,  https://github.com/NYTimes/Store/blob/master/build.gradle#L31 , do correct if I am wrong

**Comment by digitalbuddha** [comment]
Yup! Congrats you are first to try to build project outside of our building
☺️👍

**Comment by ankitPagalGuy** [comment]
Couldn't find develop branch , so created pr in master,  https://github.com/NYTimes/Store/pulls

**Comment by ankitPagalGuy** [comment]
sorry , my mistake

**Comment by digitalbuddha** [comment]
no worries, really our mistake.  You found repo a little early, its nice the code is stable but we still need to do a little cleanup on the repo :-) thank you much for trying it out.

**Comment by ankitPagalGuy** [comment]
let me know if I can contribute more , any todo list will help

**Comment by digitalbuddha** [comment]
Thank you I'll add some help wanted issues tomorrow.
